#include "crandomizer.h"

#include <ar_general_purpose/strutils.h>

CRandomizer::CRandomizer(const quint32 seed /* = 0 */ ) {
  if( 0 != seed )
    _seed = seed;
  else
    _seed = quint32( QDateTime::currentDateTime().toSecsSinceEpoch() );

  _rng = QRandomGenerator( _seed );

  buildUSCityList();
  buildUKCityList();
  buildColorList();
  buildCountryList();
  buildFoodList();
  buildPlanetList();
  buildPlanetListExt();
}


CRandomizer::~CRandomizer() {
  // Nothing to do here.
}


QString CRandomizer::alphanumeric5() {
  QChar c1( 65 + _rng.bounded( 26 ) );
  QChar c2( 65+ _rng.bounded( 26 ) );
  int i = _rng.bounded( 1000 );

  return QStringLiteral( "%1%2%3" ).arg( c1 ).arg( c2 ).arg( paddedInt( i, 3 ) );
}


QString CRandomizer::alphanumeric( const int length ) {
  Q_UNUSED( length );
  return QStringLiteral("FIXMEWriteThisFunction");
}


int CRandomizer::randInt( const int max ) {
  return _rng.bounded( max );
}


int CRandomizer::rantInt( const int min, const int max ) {
  return _rng.bounded( min, max );
}


QStringList CRandomizer::randList( const int length, const QStringList& sourceList ) {
  QSet<QString> usedStrs;
  QStringList result;

  Q_ASSERT( length <= sourceList.length() );

  int val;
  while( true ) {
    val = _rng.bounded( sourceList.length() );

    if( !usedStrs.contains( sourceList.at( val ) ) ) {
      usedStrs.insert( sourceList.at( val ) );
      result.append( sourceList.at( val ) );
      if( length == result.length() ) {
        break;
      }
    }
  }

  return result;
}


QStringList CRandomizer::randAlphanumeric5s( const int length ) {
  QSet<QString> usedStrs;
  QStringList result;

  while( true ) {
    QString val = this->alphanumeric5();
    if( !usedStrs.contains( val ) ) {
      usedStrs.insert( val );
      result.append( val );
      if( length == result.length() ) {
        break;
      }
    }
  }

  return result;
}


QList<int> CRandomizer::randInts( const int length, const int min, const int max ) {
  QSet<int> usedVals;
  QList<int> result;

  int val;
  while( true ) {
    val = _rng.bounded( min, max );
    if( !usedVals.contains( val ) ) {
      usedVals.insert( val );
      result.append( val );
      if( length == result.length() ) {
        break;
      }
    }
  }

  return result;
}



void CRandomizer::buildPlanetList() {
  _allPlanets
    << QStringLiteral("Mercury")
    << QStringLiteral("Venus")
    << QStringLiteral("Earth")
    << QStringLiteral("Mars")
    << QStringLiteral("Jupiter")
    << QStringLiteral("Saturn")
    << QStringLiteral("Neptune")
    << QStringLiteral("Uranus")
    << QStringLiteral("Pluto")
    << QStringLiteral("Ceres")
    << QStringLiteral("Haumea")
    << QStringLiteral("Makemake")
    << QStringLiteral("Eris")
  ;
}


void CRandomizer::buildPlanetListExt() {
  _allPlanetsExt
    << _allPlanets
    << QStringLiteral("Alderaan")
    << QStringLiteral("Bespin")
    << QStringLiteral("Cantonica")
    << QStringLiteral("Christophsis")
    << QStringLiteral("Corellia")
    << QStringLiteral("Coruscant")
    << QStringLiteral("Dagobah")
    << QStringLiteral("Eadu")
    << QStringLiteral("Endor")
    << QStringLiteral("Felucia")
    << QStringLiteral("Geonosis")
    << QStringLiteral("Hoth")
    << QStringLiteral("Jakku")
    << QStringLiteral("Jedha")
    << QStringLiteral("Kamino")
    << QStringLiteral("Kashyyyk")
    << QStringLiteral("Mimban")
    << QStringLiteral("Mustafar")
    << QStringLiteral("Mygeeto")
    << QStringLiteral("Naboo")
    << QStringLiteral("Savareen")
    << QStringLiteral("Scarif")
    << QStringLiteral("Takodana")
    << QStringLiteral("Tatooine")
    << QStringLiteral("Utapau")
    << QStringLiteral("Wobani")
    << QStringLiteral("Yavin")
    << QStringLiteral("Anoat")
    << QStringLiteral("Corellia")
    << QStringLiteral("Dantooine")
    << QStringLiteral("Iego")
    << QStringLiteral("Kessel")
    << QStringLiteral("Malastare")
    << QStringLiteral("Subterrel")
    << QStringLiteral("Sullust")
  ;
}


void CRandomizer::buildUKCityList() {
  _allUKCities
    << QStringLiteral("London")
    << QStringLiteral("Birmingham")
    << QStringLiteral("Glasgow")
    << QStringLiteral("Leeds")
    << QStringLiteral("Bristol")
    << QStringLiteral("Liverpool")
    << QStringLiteral("Manchester")
    << QStringLiteral("Sheffield")
    << QStringLiteral("Edinburgh")
    << QStringLiteral("Cardiff")
    << QStringLiteral("Leicester")
    << QStringLiteral("Stoke-on-Trent")
    << QStringLiteral("Bradford")
    << QStringLiteral("Coventry")
    << QStringLiteral("Nottingham")
    << QStringLiteral("Kingston-upon-Hull")
    << QStringLiteral("Belfast")
    << QStringLiteral("Newcastle-upon-Tyne")
    << QStringLiteral("Sunderland")
    << QStringLiteral("Brighton")
    << QStringLiteral("Derby")
    << QStringLiteral("Plymouth")
    << QStringLiteral("Wolverhampton")
    << QStringLiteral("Southampton")
    << QStringLiteral("Swansea")
    << QStringLiteral("Salford")
    << QStringLiteral("Portsmouth")
    << QStringLiteral("Milton Keynes")
    << QStringLiteral("Aberdeen")
    << QStringLiteral("Reading")
    << QStringLiteral("Northampton")
    << QStringLiteral("Luton")
    << QStringLiteral("Swindon")
    << QStringLiteral("Warrington")
    << QStringLiteral("Dudley")
    << QStringLiteral("York")
    << QStringLiteral("Bolton")
    << QStringLiteral("Stockton-on-Tees")
    << QStringLiteral("Preston")
    << QStringLiteral("Bournemouth")
    << QStringLiteral("Norwich")
    << QStringLiteral("Middlesbrough")
    << QStringLiteral("Peterborough")
    << QStringLiteral("Southend-on-Sea")
    << QStringLiteral("Walsall")
    << QStringLiteral("Colchester")
    << QStringLiteral("Mansfield")
    << QStringLiteral("Telford")
    << QStringLiteral("Ipswich")
    << QStringLiteral("Huddersfield")
    << QStringLiteral("Dundee")
    << QStringLiteral("Oxford")
    << QStringLiteral("Doncaster")
    << QStringLiteral("Chelmsford")
    << QStringLiteral("Cambridge")
    << QStringLiteral("Maidstone")
    << QStringLiteral("Slough")
    << QStringLiteral("Poole")
    << QStringLiteral("Blackburn")
    << QStringLiteral("Chesterfield")
    << QStringLiteral("Blackpool")
    << QStringLiteral("Newport")
    << QStringLiteral("Birkenhead")
    << QStringLiteral("Hastings")
    << QStringLiteral("Bedford")
    << QStringLiteral("Gloucester")
    << QStringLiteral("West Bromwich")
    << QStringLiteral("Worcester")
    << QStringLiteral("Sale")
    << QStringLiteral("Nuneaton")
    << QStringLiteral("Watford")
    << QStringLiteral("Exeter")
    << QStringLiteral("Solihull")
    << QStringLiteral("Chester")
    << QStringLiteral("High Wycombe")
    << QStringLiteral("Gateshead")
    << QStringLiteral("Southport")
    << QStringLiteral("Rotherham")
    << QStringLiteral("Cheltenham")
    << QStringLiteral("Hove")
    << QStringLiteral("Eastbourne")
    << QStringLiteral("Worthing")
    << QStringLiteral("Londonderry")
    << QStringLiteral("Rochdale")
    << QStringLiteral("Basingstoke")
    << QStringLiteral("Basildon")
    << QStringLiteral("Crawley")
    << QStringLiteral("Falkirk")
    << QStringLiteral("Stockport")
    << QStringLiteral("Darlington")
    << QStringLiteral("Woking")
    << QStringLiteral("Lincoln")
    << QStringLiteral("Gillingham")
    << QStringLiteral("Wigan")
    << QStringLiteral("Oldham")
    << QStringLiteral("Tamworth")
    << QStringLiteral("Carlisle")
    << QStringLiteral("Dartford")
    << QStringLiteral("Wakefield")
    << QStringLiteral("Rayleigh")
    << QStringLiteral("Hemel Hempstead")
    << QStringLiteral("Bath")
    << QStringLiteral("Weymouth")
    << QStringLiteral("Hartlepool")
    << QStringLiteral("Barnsley")
    << QStringLiteral("Stevenage")
    << QStringLiteral("Grimsby")
    << QStringLiteral("Halifax")
    << QStringLiteral("Redditch")
    << QStringLiteral("Weston-super-Mare")
    << QStringLiteral("Harlow")
    << QStringLiteral("Burnley")
    << QStringLiteral("Scunthorpe")
    << QStringLiteral("Eastleigh")
    << QStringLiteral("Bracknell")
    << QStringLiteral("Bury")
    << QStringLiteral("Guildford")
    << QStringLiteral("Paisley")
    << QStringLiteral("Chatham")
    << QStringLiteral("South Shields")
    << QStringLiteral("Newcastle-under-Lyme")
    << QStringLiteral("East Kilbride")
    << QStringLiteral("Harrogate")
    << QStringLiteral("Lisburn")
    << QStringLiteral("Burton-upon-Trent")
    << QStringLiteral("Aylesbury")
    << QStringLiteral("Crewe")
    << QStringLiteral("Shrewsbury")
    << QStringLiteral("Gosport")
    << QStringLiteral("Lowestoft")
    << QStringLiteral("Rugby")
    << QStringLiteral("Stafford")
    << QStringLiteral("Rossendale")
    << QStringLiteral("Cannock")
    << QStringLiteral("Tynemouth")
    << QStringLiteral("Washington")
    << QStringLiteral("Grays")
    << QStringLiteral("Walton-on-Thames")
    << QStringLiteral("Craigavon")
    << QStringLiteral("Farnborough")
    << QStringLiteral("Paignton")
    << QStringLiteral("Waterlooville")
    << QStringLiteral("Runcorn")
    << QStringLiteral("Bognor Regis")
    << QStringLiteral("Maidenhead")
    << QStringLiteral("Stourbridge")
    << QStringLiteral("Rochester")
    << QStringLiteral("Dewsbury")
    << QStringLiteral("Scarborough")
    << QStringLiteral("Newtownabbey")
    << QStringLiteral("Wrexham")
    << QStringLiteral("Widnes")
    << QStringLiteral("Margate")
    << QStringLiteral("Ellesmere Port")
    << QStringLiteral("Taunton")
    << QStringLiteral("Hereford")
    << QStringLiteral("Wallasey")
    << QStringLiteral("Bangor")
    << QStringLiteral("Loughborough")
    << QStringLiteral("Halesowen")
    << QStringLiteral("Royal Tunbridge")
    << QStringLiteral("Bebington")
    << QStringLiteral("Aldershot")
    << QStringLiteral("Macclesfield")
    << QStringLiteral("Livingston")
    << QStringLiteral("Kettering")
    << QStringLiteral("Littlehampton")
    << QStringLiteral("Kidderminster")
    << QStringLiteral("Gravesend")
    << QStringLiteral("Corby")
    << QStringLiteral("Canterbury")
    << QStringLiteral("Barry")
    << QStringLiteral("Christchurch")
    << QStringLiteral("Keighley")
    << QStringLiteral("Hamilton")
    << QStringLiteral("Brentwood")
    << QStringLiteral("Ewell")
    << QStringLiteral("Beeston")
    << QStringLiteral("Bootle")
    << QStringLiteral("Esher")
    << QStringLiteral("Kingswinford")
    << QStringLiteral("Neath")
    << QStringLiteral("Clacton-on-Sea")
    << QStringLiteral("Crosby")
    << QStringLiteral("Kirkcaldy")
    << QStringLiteral("Dunfermline")
    << QStringLiteral("Carlton")
    << QStringLiteral("Wellingborough")
    << QStringLiteral("Torquay")
    << QStringLiteral("Sittingbourne")
    << QStringLiteral("Smethwick")
    << QStringLiteral("Shoreham-by-Sea")
    << QStringLiteral("Inverness")
    << QStringLiteral("Lancaster")
    << QStringLiteral("Horsham")
    << QStringLiteral("Ayr")
    << QStringLiteral("Perth")
    << QStringLiteral("Cwmbrân"
)    << QStringLiteral("Banbury")
    << QStringLiteral("Llanelli")
    << QStringLiteral("Kilmarnock")
    << QStringLiteral("Barrow-in-Furness")
    << QStringLiteral("Sutton-in-Ashfield")
    << QStringLiteral("Cheshunt")
    << QStringLiteral("West Bridgford")
    << QStringLiteral("Northwich")
    << QStringLiteral("Ashton-under-Lyne")
    << QStringLiteral("Winchester")
    << QStringLiteral("Havant")
    << QStringLiteral("Salisbury")
    << QStringLiteral("Greenock")
    << QStringLiteral("Coatbridge")
    << QStringLiteral("Wallsend")
    << QStringLiteral("Merthyr Tydfil")
    << QStringLiteral("Jarrow")
    << QStringLiteral("Whiteley")
    << QStringLiteral("Middleton")
    << QStringLiteral("Kirkby")
    << QStringLiteral("Wokingham")
    << QStringLiteral("Bexhill-on-Sea")
    << QStringLiteral("Hoddesdon")
    << QStringLiteral("Fareham")
    << QStringLiteral("Grantham")
    << QStringLiteral("Worksop")
    << QStringLiteral("Andover")
    << QStringLiteral("Dover")
    << QStringLiteral("Braintree")
    << QStringLiteral("Caerphilly")
    << QStringLiteral("Boston")
    << QStringLiteral("Bridgwater")
    << QStringLiteral("Ramsgate")
    << QStringLiteral("Irvine")
    << QStringLiteral("Cleethorpes")
    << QStringLiteral("Trowbridge")
    << QStringLiteral("Swadlincote")
    << QStringLiteral("Glenrothes")
    << QStringLiteral("Castleford")
    << QStringLiteral("Leyland")
    << QStringLiteral("Newbury")
    << QStringLiteral("Eccles")
    << QStringLiteral("Fleet")
    << QStringLiteral("Great Yarmouth")
    << QStringLiteral("Tonbridge")
    << QStringLiteral("Ilkeston")
    << QStringLiteral("Herne Bay")
    << QStringLiteral("Abingdon-on-Thames")
    << QStringLiteral("Camberley")
    << QStringLiteral("Long Eaton")
    << QStringLiteral("Hatfield")
    << QStringLiteral("Blyth")
    << QStringLiteral("Port Talbot")
    << QStringLiteral("Chester-le-Street")
    << QStringLiteral("Airdrie")
    << QStringLiteral("Newark-on-Trent")
    << QStringLiteral("Redcar")
    << QStringLiteral("Whitley Bay")
    << QStringLiteral("Chorley")
    << QStringLiteral("Wilmslow")
    << QStringLiteral("Borehamwood")
    << QStringLiteral("Accrington")
    << QStringLiteral("Chadderton")
    << QStringLiteral("Romiley")
    << QStringLiteral("Coalville")
    << QStringLiteral("Redhill")
    << QStringLiteral("Skelmersdale")
    << QStringLiteral("Exmouth")
    << QStringLiteral("Billericay")
    << QStringLiteral("Hitchin")
    << QStringLiteral("Tyldesley")
    << QStringLiteral("Hyde")
    << QStringLiteral("Haywards Heath")
    << QStringLiteral("St Helier")
    << QStringLiteral("Wickford")
    << QStringLiteral("Bromsgrove")
    << QStringLiteral("Brighouse")
    << QStringLiteral("Huyton")
    << QStringLiteral("Chippenham")
    << QStringLiteral("Strood")
    << QStringLiteral("Glossop")
    << QStringLiteral("Dumfries")
    << QStringLiteral("Lichfield")
    << QStringLiteral("Stroud")
    << QStringLiteral("Bicester")
    << QStringLiteral("Pudsey")
    << QStringLiteral("Hucknall")
    << QStringLiteral("Whitstable")
    << QStringLiteral("Motherwell")
    << QStringLiteral("Prestwich")
    << QStringLiteral("Barnstaple")
    << QStringLiteral("Spalding")
    << QStringLiteral("Wisbech")
    << QStringLiteral("Epsom")
    << QStringLiteral("Brierley Hill")
    << QStringLiteral("Rutherglen")
    << QStringLiteral("Warwick")
    << QStringLiteral("Pitsea")
    << QStringLiteral("Loughton")
    << QStringLiteral("Stanford-le-Hope")
    << QStringLiteral("Burgess Hill")
    << QStringLiteral("Beverley")
    << QStringLiteral("Wishaw")
    << QStringLiteral("Colwyn Bay")
    << QStringLiteral("Harpenden")
    << QStringLiteral("George Town")
    << QStringLiteral("Dunstable")
    << QStringLiteral("Yate")
    << QStringLiteral("Radcliffe")
    << QStringLiteral("Newry")
    << QStringLiteral("Weybridge")
    << QStringLiteral("Bilston")
    << QStringLiteral("Ballymena")
    << QStringLiteral("Gibraltar")
    << QStringLiteral("Pontefract")
    << QStringLiteral("Burntwood")
    << QStringLiteral("Witney")
    << QStringLiteral("East Grinstead")
    << QStringLiteral("Carrickfergus")
    << QStringLiteral("Clydebank")
    << QStringLiteral("Totton")
    << QStringLiteral("Chichester")
    << QStringLiteral("Kendal")
    << QStringLiteral("Newtownards")
    << QStringLiteral("Heywood")
    << QStringLiteral("Darwen")
    << QStringLiteral("Ashford")
    << QStringLiteral("Ashington")
    << QStringLiteral("Douglas")
    << QStringLiteral("Stratford-upon-Avon")
    << QStringLiteral("Bradley Stoke")
    << QStringLiteral("Cramlington")
    << QStringLiteral("Penarth")
    << QStringLiteral("Melton Mowbray")
    << QStringLiteral("Haverhill")
    << QStringLiteral("Cambuslang")
    << QStringLiteral("Farnworth")
    << QStringLiteral("Kirkby-in-Ashfield")
    << QStringLiteral("Didcot")
    << QStringLiteral("Hertford")
    << QStringLiteral("Stalybridge")
    << QStringLiteral("Frome")
    << QStringLiteral("Ryde")
    << QStringLiteral("Thatcham")
    << QStringLiteral("Staines-upon-Thames")
    << QStringLiteral("Heanor")
    << QStringLiteral("Farnham")
    << QStringLiteral("Newton Abbot")
    << QStringLiteral("Swinton")
    << QStringLiteral("Fleetwood")
    << QStringLiteral("Witham")
    << QStringLiteral("Bushey")
    << QStringLiteral("Rhyl")
    << QStringLiteral("Skegness")
    << QStringLiteral("Consett")
    << QStringLiteral("Gorleston-on-Sea")
    << QStringLiteral("Coleraine")
    << QStringLiteral("Saddleworth")
    << QStringLiteral("Droylsden")
    << QStringLiteral("Westhoughton")
    << QStringLiteral("Ormskirk")
    << QStringLiteral("Blackwood")
    << QStringLiteral("Whitehaven")
    << QStringLiteral("Rickmansworth")
    << QStringLiteral("Oldbury")
    << QStringLiteral("Huntingdon")
    << QStringLiteral("Arbroath")
    << QStringLiteral("Daventry")
    << QStringLiteral("St Austell")
    << QStringLiteral("Portishead")
    << QStringLiteral("Broadstairs")
    << QStringLiteral("Lurgan")
    << QStringLiteral("Belper")
    << QStringLiteral("Wombwell")
    << QStringLiteral("Formby")
    << QStringLiteral("Burnham-on-Sea")
    << QStringLiteral("Elgin")
    << QStringLiteral("Rawtenstall")
    << QStringLiteral("Coseley")
    << QStringLiteral("Amersham")
    << QStringLiteral("Market Harborough")
    << QStringLiteral("Alfreton")
    << QStringLiteral("Horley")
    << QStringLiteral("Godalming")
    << QStringLiteral("Falmouth")
    << QStringLiteral("Musselburgh")
    << QStringLiteral("Bingley")
    << QStringLiteral("Seaham")
    << QStringLiteral("Chesham")
    << QStringLiteral("Sudbury")
    << QStringLiteral("Reigate")
    << QStringLiteral("Buxton")
    << QStringLiteral("Workington")
    << QStringLiteral("Retford")
    << QStringLiteral("Antrim")
    << QStringLiteral("Maldon")
    << QStringLiteral("Omagh")
    << QStringLiteral("Ossett")
    << QStringLiteral("Walkden")
    << QStringLiteral("March")
    << QStringLiteral("Clevedon")
    << QStringLiteral("Stanley")
    << QStringLiteral("Whitefield")
    << QStringLiteral("Dukinfield")
    << QStringLiteral("Gainsborough")
    << QStringLiteral("Goole")
    << QStringLiteral("Dereham")
    << QStringLiteral("Berkhamsted")
    << QStringLiteral("Crowborough")
    << QStringLiteral("Sandhurst")
    << QStringLiteral("Camborne")
    << QStringLiteral("Wellington")
    << QStringLiteral("Newmarket")
    << QStringLiteral("Bathgate")
    << QStringLiteral("Truro")
    << QStringLiteral("Penzance")
    << QStringLiteral("Newquay")
    << QStringLiteral("Dumbarton")
    << QStringLiteral("New Milton")
    << QStringLiteral("Irlam")
    << QStringLiteral("Portslade-by-Sea")
    << QStringLiteral("Redruth")
    << QStringLiteral("Tewkesbury")
    << QStringLiteral("Harwich")
    << QStringLiteral("Stamford")
    << QStringLiteral("Kirkintilloch")
    << QStringLiteral("Leek")
    << QStringLiteral("Tiverton")
    << QStringLiteral("Hazel Grove")
    << QStringLiteral("Eastwood")
    << QStringLiteral("Melksham")
    << QStringLiteral("Kempston")
    << QStringLiteral("Adwick-le-Street")
    << QStringLiteral("Hebburn")
    << QStringLiteral("Ely")
    << QStringLiteral("Molesey")
    << QStringLiteral("Dorchester")
    << QStringLiteral("Ware")
    << QStringLiteral("Minster-on-Sea")
    << QStringLiteral("Waltham Abbey")
    << QStringLiteral("Oswestry")
    << QStringLiteral("Lancing")
    << QStringLiteral("Peterhead")
    << QStringLiteral("Rawmarsh")
    << QStringLiteral("Prestatyn")
    << QStringLiteral("Johnstone")
    << QStringLiteral("Alton")
    << QStringLiteral("Aberystwyth")
    << QStringLiteral("Devizes")
    << QStringLiteral("Sunbury-on-Thames")
    << QStringLiteral("Bideford")
    << QStringLiteral("Spennymoor")
    << QStringLiteral("Hoyland")
    << QStringLiteral("Selby")
    << QStringLiteral("Poulton-le-Fylde")
    << QStringLiteral("Grangemouth")
    << QStringLiteral("Sleaford")
    << QStringLiteral("Lewes")
    << QStringLiteral("Blantyre")
    << QStringLiteral("Nantwich")
    << QStringLiteral("Dorking")
    << QStringLiteral("Romsey")
    << QStringLiteral("Guisborough")
    << QStringLiteral("Northallerton")
    << QStringLiteral("Brixham")
    << QStringLiteral("Haydock")
    << QStringLiteral("Louth")
    << QStringLiteral("St Ives")
    << QStringLiteral("Ripon")
    << QStringLiteral("Cirencester")
    << QStringLiteral("Swanley")
    << QStringLiteral("Nailsea")
    << QStringLiteral("Banbridge")
    << QStringLiteral("Haslingden")
    << QStringLiteral("Penicuik")
    << QStringLiteral("Carmarthen")
    << QStringLiteral("Tadley")
    << QStringLiteral("Royston")
    << QStringLiteral("Carterton")
    << QStringLiteral("Keynsham")
    << QStringLiteral("Larkhall")
    << QStringLiteral("Saltash")
    << QStringLiteral("Knaresborough")
    << QStringLiteral("Llandudno")
    << QStringLiteral("Broxburn")
    << QStringLiteral("Lymington")
    << QStringLiteral("Uckfield")
    << QStringLiteral("Saffron Walden")
    << QStringLiteral("Cottingham")
    << QStringLiteral("Wimborne Minster")
    << QStringLiteral("Teignmouth")
    << QStringLiteral("Hythe")
    << QStringLiteral("Neston")
    << QStringLiteral("Kidlington")
    << QStringLiteral("Galashiels")
    << QStringLiteral("Petersfield")
    << QStringLiteral("Matlock")
    << QStringLiteral("Flint")
    << QStringLiteral("Prestwick")
    << QStringLiteral("Bo’ness"
 )   << QStringLiteral("Tredegar")
    << QStringLiteral("Marlow")
    << QStringLiteral("Ilkley")
    << QStringLiteral("Clitheroe")
    << QStringLiteral("Armagh")
    << QStringLiteral("Frampton Cotterell")
    << QStringLiteral("Porth")
    << QStringLiteral("Skipton")
    << QStringLiteral("Haverfordwest")
    << QStringLiteral("Morpeth")
    << QStringLiteral("Dungannon")
    << QStringLiteral("Dunscroft")
    << QStringLiteral("Hawick")
    << QStringLiteral("Helensburgh")
    << QStringLiteral("West Cowes")
    << QStringLiteral("Forfar")
    << QStringLiteral("Dundonald")
    << QStringLiteral("Ringwood")
    << QStringLiteral("Strabane")
    << QStringLiteral("Beccles")
    << QStringLiteral("Houghton-le-Spring")
    << QStringLiteral("Beaconsfield")
    << QStringLiteral("Enniskillen")
    << QStringLiteral("Chertsey")
    << QStringLiteral("Blackfield")
    << QStringLiteral("Standish")
    << QStringLiteral("Whiston")
    << QStringLiteral("Milford Haven")
    << QStringLiteral("Oxted")
    << QStringLiteral("Corsham")
    << QStringLiteral("Abergavenny")
    << QStringLiteral("Verwood")
    << QStringLiteral("Alsager")
    << QStringLiteral("Bacup")
    << QStringLiteral("Pensby")
    << QStringLiteral("Berwick-upon-Tweed")
    << QStringLiteral("Whitby")
    << QStringLiteral("Fraserburgh")
    << QStringLiteral("Uttoxeter")
    << QStringLiteral("Chard")
    << QStringLiteral("Alexandria")
    << QStringLiteral("Milngavie")
    << QStringLiteral("Saltdean")
    << QStringLiteral("Street")
    << QStringLiteral("Inverurie")
    << QStringLiteral("Bromborough")
    << QStringLiteral("Tividale")
    << QStringLiteral("Mablethorpe")
    << QStringLiteral("North Walsham")
    << QStringLiteral("Ashby-de-la-Zouch")
    << QStringLiteral("Chepstow")
    << QStringLiteral("Bridgnorth")
    << QStringLiteral("Walton-on-the-Naze")
    << QStringLiteral("Cookstown")
    << QStringLiteral("Montrose")
    << QStringLiteral("Sheerness")
    << QStringLiteral("Kirkham")
    << QStringLiteral("Halstead")
    << QStringLiteral("Sandown")
    << QStringLiteral("Ivybridge")
    << QStringLiteral("Bolsover")
    << QStringLiteral("Bargoed")
    << QStringLiteral("Stoke Gifford")
    << QStringLiteral("Henley-on-Thames")
    << QStringLiteral("Stonehaven")
    << QStringLiteral("Holyhead")
    << QStringLiteral("Cowdenbeath")
    << QStringLiteral("Carnoustie")
    << QStringLiteral("Newtown")
    << QStringLiteral("Knowsley")
    << QStringLiteral("Thame")
    << QStringLiteral("Dawlish")
    << QStringLiteral("Helston")
    << QStringLiteral("Wetherby")
    << QStringLiteral("Prudhoe")
    << QStringLiteral("Ilfracombe")
    << QStringLiteral("Bodden Town")
    << QStringLiteral("Westhill")
    << QStringLiteral("Leominster")
    << QStringLiteral("Oakham")
    << QStringLiteral("Hoylake")
    << QStringLiteral("Shirebrook")
    << QStringLiteral("Downham Market")
    << QStringLiteral("Immingham")
    << QStringLiteral("Downpatrick")
    << QStringLiteral("Banstead")
    << QStringLiteral("Gourock")
    << QStringLiteral("Filton")
    << QStringLiteral("Ross-on-Wye")
    << QStringLiteral("Selsey")
    << QStringLiteral("Wells")
    << QStringLiteral("Whitburn")
    << QStringLiteral("Patchway")
    << QStringLiteral("Swanage")
    << QStringLiteral("Kingsteignton")
    << QStringLiteral("Shepton Mallet")
    << QStringLiteral("South Elmsall")
    << QStringLiteral("Chigwell")
    << QStringLiteral("Chatteris")
    << QStringLiteral("Epping")
    << QStringLiteral("West Bay")
    << QStringLiteral("Baldock")
    << QStringLiteral("Ellon")
    << QStringLiteral("Ystradgynlais")
    << QStringLiteral("Ascot")
    << QStringLiteral("Amesbury")
    << QStringLiteral("Monmouth")
    << QStringLiteral("Waltham Cross")
    << QStringLiteral("Mold")
    << QStringLiteral("Thirsk")
    << QStringLiteral("Lutterworth")
    << QStringLiteral("Worth")
    << QStringLiteral("Dalgety Bay")
    << QStringLiteral("Ollerton")
    << QStringLiteral("Diss")
    << QStringLiteral("Penistone")
    << QStringLiteral("Sawbridgeworth")
    << QStringLiteral("Woodingdean")
    << QStringLiteral("Pembroke Dock")
    << QStringLiteral("Polesworth")
    << QStringLiteral("Newbridge")
    << QStringLiteral("Maryport")
    << QStringLiteral("Caernarfon")
    << QStringLiteral("Cupar")
    << QStringLiteral("Onchan")
    << QStringLiteral("Abergele")
    << QStringLiteral("Yaxley")
    << QStringLiteral("Tidworth")
    << QStringLiteral("Soham")
    << QStringLiteral("Bradford-on-Avon")
    << QStringLiteral("Cockermouth")
    << QStringLiteral("Larbert")
    << QStringLiteral("Worsley")
    << QStringLiteral("Shanklin")
    << QStringLiteral("Blairgowrie")
    << QStringLiteral("Hockley")
    << QStringLiteral("Magherafelt")
    << QStringLiteral("Ledbury")
    << QStringLiteral("Dunblane")
    << QStringLiteral("Southwater")
    << QStringLiteral("Uphall")
    << QStringLiteral("Oban")
    << QStringLiteral("South Kirkby")
    << QStringLiteral("Denbigh")
    << QStringLiteral("Dunbar")
    << QStringLiteral("Glastonbury")
    << QStringLiteral("Hornsea")
    << QStringLiteral("Llantwit Major")
    << QStringLiteral("Watton")
    << QStringLiteral("Richmond")
    << QStringLiteral("Peebles")
    << QStringLiteral("Brecon")
    << QStringLiteral("Hayle")
    << QStringLiteral("Alnwick")
    << QStringLiteral("Marlborough")
    << QStringLiteral("Totnes")
    << QStringLiteral("Iver Heath")
    << QStringLiteral("Rhymney")
    << QStringLiteral("Cromer")
    << QStringLiteral("Thurso")
    << QStringLiteral("Ramsey")
    << QStringLiteral("Highworth")
    << QStringLiteral("Crediton")
    << QStringLiteral("Freshwater")
    << QStringLiteral("Heswall")
    << QStringLiteral("Oaklands")
    << QStringLiteral("Okehampton")
    << QStringLiteral("Warrenpoint")
    << QStringLiteral("Launceston")
    << QStringLiteral("Pembroke")
    << QStringLiteral("Longridge")
    << QStringLiteral("Dinas Powys")
    << QStringLiteral("Brechin")
    << QStringLiteral("Murton")
    << QStringLiteral("Wraysbury")
    << QStringLiteral("Crieff")
    << QStringLiteral("Stonehouse")
    << QStringLiteral("Shaftesbury")
    << QStringLiteral("Girvan")
    << QStringLiteral("Portlethen")
    << QStringLiteral("Wick")
    << QStringLiteral("Wendover")
    << QStringLiteral("Lochgelly")
    << QStringLiteral("Faringdon")
    << QStringLiteral("Kirkwall")
    << QStringLiteral("East Cowes")
    << QStringLiteral("Bolton-le-Sands")
    << QStringLiteral("Lerwick")
    << QStringLiteral("Alcester")
    << QStringLiteral("Burnham-on-Crouch")
    << QStringLiteral("Lightwater")
    << QStringLiteral("Brigg")
    << QStringLiteral("Bolton-upon-Dearne")
    << QStringLiteral("Sherburn-in-Elmet")
    << QStringLiteral("Portrush")
    << QStringLiteral("North Berwick")
    << QStringLiteral("Kilkeel")
    << QStringLiteral("Carryduff")
    << QStringLiteral("Godmanchester")
    << QStringLiteral("Tadcaster")
    << QStringLiteral("Castle Donington")
    << QStringLiteral("Coleshill")
    << QStringLiteral("Road Town")
    << QStringLiteral("Malmesbury")
    << QStringLiteral("Stainforth")
    << QStringLiteral("Burntisland")
    << QStringLiteral("Ventnor")
    << QStringLiteral("Studley")
    << QStringLiteral("Withernsea")
    << QStringLiteral("Kingsbridge")
    << QStringLiteral("Chipping Ongar")
    << QStringLiteral("Kirriemuir")
    << QStringLiteral("Waltham")
    << QStringLiteral("Saltburn-by-the-Sea")
    << QStringLiteral("Welshpool")
    << QStringLiteral("Fort William")
    << QStringLiteral("Wigton")
    << QStringLiteral("Selkirk")
    << QStringLiteral("Oundle")
    << QStringLiteral("Chipping Norton")
    << QStringLiteral("Stornoway")
    << QStringLiteral("Great Torrington")
    << QStringLiteral("Kelso")
    << QStringLiteral("Dromore")
    << QStringLiteral("Coalisland")
    << QStringLiteral("Hemsby")
    << QStringLiteral("Hethersett")
    << QStringLiteral("Greenisland")
    << QStringLiteral("Wareham")
    << QStringLiteral("Chinnor")
    << QStringLiteral("Wincanton")
    << QStringLiteral("West Clandon")
    << QStringLiteral("Llandrindod Wells")
    << QStringLiteral("Northwood")
    << QStringLiteral("Cheddar")
    << QStringLiteral("Appley Bridge")
    << QStringLiteral("Church")
    << QStringLiteral("Shevington")
    << QStringLiteral("Looe")
    << QStringLiteral("Cookham")
    << QStringLiteral("Hungerford")
    << QStringLiteral("Peel")
    << QStringLiteral("Bude")
    << QStringLiteral("Dartmouth")
    << QStringLiteral("Menai Bridge")
    << QStringLiteral("Datchet")
    << QStringLiteral("Winterton")
    << QStringLiteral("Kinross")
    << QStringLiteral("Llangefni")
    << QStringLiteral("Campbeltown")
    << QStringLiteral("Blaina")
    << QStringLiteral("Market Rasen")
    << QStringLiteral("Rye")
    << QStringLiteral("Keith")
    << QStringLiteral("Bovey Tracey")
    << QStringLiteral("Coggeshall")
    << QStringLiteral("Lyme Regis")
    << QStringLiteral("Frinton-on-Sea")
    << QStringLiteral("High Lane")
    << QStringLiteral("Sedgefield")
    << QStringLiteral("Irchester")
    << QStringLiteral("Chipping Sodbury")
    << QStringLiteral("Glyn-Neath")
    << QStringLiteral("Send")
    << QStringLiteral("Bramley")
    << QStringLiteral("New Tredegar")
    << QStringLiteral("Cardigan")
    << QStringLiteral("Castle Douglas")
    << QStringLiteral("Lennoxtown")
    << QStringLiteral("Hextable")
    << QStringLiteral("Banff")
    << QStringLiteral("Invergordon")
    << QStringLiteral("Saltford")
    << QStringLiteral("Stokenchurch")
    << QStringLiteral("Jedburgh")
    << QStringLiteral("Chudleigh")
    << QStringLiteral("Macduff")
    << QStringLiteral("Keele")
    << QStringLiteral("Lydd")
    << QStringLiteral("Maghera")
    << QStringLiteral("Conwy")
    << QStringLiteral("Whitehead")
    << QStringLiteral("Tenbury Wells")
    << QStringLiteral("Almondsbury")
    << QStringLiteral("Eye")
    << QStringLiteral("Parkgate")
    << QStringLiteral("Cockburn Town")
    << QStringLiteral("Bembridge")
    << QStringLiteral("Ellesmere")
    << QStringLiteral("Moira")
    << QStringLiteral("Settle")
    << QStringLiteral("Tylorstown")
    << QStringLiteral("Pewsey")
    << QStringLiteral("Barnston")
    << QStringLiteral("Boroughbridge")
    << QStringLiteral("Wilton")
    << QStringLiteral("Brockenhurst")
    << QStringLiteral("Carisbrooke")
    << QStringLiteral("Eyemouth")
    << QStringLiteral("Sedbury")
    << QStringLiteral("Port Erin")
    << QStringLiteral("Stamford Bridge")
    << QStringLiteral("Welwyn")
    << QStringLiteral("Messingham")
    << QStringLiteral("Spilsby")
    << QStringLiteral("Fishguard")
    << QStringLiteral("Queenborough")
    << QStringLiteral("Little Neston")
    << QStringLiteral("Takeley")
    << QStringLiteral("St Asaph")
    << QStringLiteral("Kirkcudbright")
    << QStringLiteral("Ashburton")
    << QStringLiteral("Somerton")
    << QStringLiteral("Ahoghill")
    << QStringLiteral("Buckfastleigh")
    << QStringLiteral("Fairford")
    << QStringLiteral("Castle Cary")
    << QStringLiteral("Walton")
    << QStringLiteral("Dordon")
    << QStringLiteral("Amlwch")
    << QStringLiteral("West Calder")
    << QStringLiteral("Newton")
    << QStringLiteral("Gayton")
    << QStringLiteral("Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch")
    << QStringLiteral("Castletown")
    << QStringLiteral("Langford")
    << QStringLiteral("Beaminster")
    << QStringLiteral("Langport")
    << QStringLiteral("Minster")
    << QStringLiteral("Bruton")
    << QStringLiteral("Porthmadog")
    << QStringLiteral("Castlewellan")
    << QStringLiteral("Minchinhampton")
    << QStringLiteral("Over")
    << QStringLiteral("Charlbury")
    << QStringLiteral("Builth Wells")
    << QStringLiteral("Kidwelly")
    << QStringLiteral("Stoke Mandeville")
    << QStringLiteral("Saundersfoot")
    << QStringLiteral("Duns")
    << QStringLiteral("Mere")
    << QStringLiteral("Fairfield Park")
    << QStringLiteral("Tuxford")
    << QStringLiteral("Holsworthy")
    << QStringLiteral("Kington")
    << QStringLiteral("Highclere")
    << QStringLiteral("Tarporley")
    << QStringLiteral("Brierley")
    << QStringLiteral("Godstone")
    << QStringLiteral("Rostrevor")
    << QStringLiteral("Higher Folds")
    << QStringLiteral("Yarnton")
    << QStringLiteral("Caldercruix")
    << QStringLiteral("Presteigne")
    << QStringLiteral("Ironbridge")
    << QStringLiteral("Watlington")
    << QStringLiteral("Aspatria")
    << QStringLiteral("Ellington")
    << QStringLiteral("Valley")
    << QStringLiteral("Larkhill")
    << QStringLiteral("Lyndhurst")
    << QStringLiteral("Castledawson")
    << QStringLiteral("Watton-at-Stone")
    << QStringLiteral("Collingham")
    << QStringLiteral("Barmouth")
    << QStringLiteral("Coltishall")
    << QStringLiteral("Oakley")
    << QStringLiteral("Mevagissey")
    << QStringLiteral("Bradpole")
    << QStringLiteral("Coupar Angus")
    << QStringLiteral("Hambleton")
    << QStringLiteral("Benllech")
    << QStringLiteral("Langholm")
    << QStringLiteral("Milnthorpe")
    << QStringLiteral("Mossblown")
    << QStringLiteral("Leyburn")
    << QStringLiteral("Severn Beach")
    << QStringLiteral("Tisbury")
    << QStringLiteral("Wells-next-the-Sea")
    << QStringLiteral("Eton")
    << QStringLiteral("Duxford")
    << QStringLiteral("Sandford")
    << QStringLiteral("Odiham")
    << QStringLiteral("Wickham")
    << QStringLiteral("Halton")
    << QStringLiteral("Chipping Campden")
    << QStringLiteral("Eton Wick")
    << QStringLiteral("Hutton")
    << QStringLiteral("Elstree")
    << QStringLiteral("Comrie")
    << QStringLiteral("South Nutfield")
    << QStringLiteral("Wrotham")
    << QStringLiteral("Annalong")
    << QStringLiteral("Salcombe")
    << QStringLiteral("Moneymore")
    << QStringLiteral("Ashwell")
    << QStringLiteral("Lynemouth")
    << QStringLiteral("Hale")
    << QStringLiteral("Rhayader")
    << QStringLiteral("Draperstown")
    << QStringLiteral("East Bridgford")
    << QStringLiteral("Cold Ash")
    << QStringLiteral("Shaldon")
    << QStringLiteral("Althorpe")
    << QStringLiteral("St George")
    << QStringLiteral("West Hill")
    << QStringLiteral("Goodwick")
    << QStringLiteral("Laxey")
    << QStringLiteral("Thornhill")
    << QStringLiteral("Burton")
    << QStringLiteral("Ness")
    << QStringLiteral("Hockley Heath")
    << QStringLiteral("Calderbank")
    << QStringLiteral("Crossmaglen")
    << QStringLiteral("Ainsworth")
    << QStringLiteral("Trimsaran")
    << QStringLiteral("Stock")
    << QStringLiteral("Kilrea")
    << QStringLiteral("Ullapool")
    << QStringLiteral("Trearddur")
    << QStringLiteral("Whittlesford")
    << QStringLiteral("Crockenhill")
    << QStringLiteral("Markham")
    << QStringLiteral("Steventon")
    << QStringLiteral("Ryhall")
    << QStringLiteral("Godshill")
    << QStringLiteral("East End")
    << QStringLiteral("Balcombe")
    << QStringLiteral("Aberaeron")
    << QStringLiteral("Burnhope")
    << QStringLiteral("Dobwalls")
    << QStringLiteral("Twyford")
    << QStringLiteral("Dorchester-on-Thames")
    << QStringLiteral("Wingrave")
    << QStringLiteral("Kirkby-le-Soken")
    << QStringLiteral("Horspath")
    << QStringLiteral("Beaumaris")
    << QStringLiteral("Box Hill")
    << QStringLiteral("Fivemiletown")
    << QStringLiteral("Potten End")
    << QStringLiteral("Corfe Castle")
    << QStringLiteral("Barford")
    << QStringLiteral("Garsington")
    << QStringLiteral("Castlerock")
    << QStringLiteral("Garvagh")
  ;
}


void CRandomizer::buildColorList() {
  _allColors
    << QStringLiteral("White")
    << QStringLiteral("Pearl")
    << QStringLiteral("Alabaster")
    << QStringLiteral("Snow")
    << QStringLiteral("Ivory")
    << QStringLiteral("Cream")
    << QStringLiteral("Eggshell")
    << QStringLiteral("Cotton")
    << QStringLiteral("Chiffon")
    << QStringLiteral("Salt")
    << QStringLiteral("Lace")
    << QStringLiteral("Coconut")
    << QStringLiteral("Linen")
    << QStringLiteral("Bone")
    << QStringLiteral("Daisy")
    << QStringLiteral("Powder")
    << QStringLiteral("Frost")
    << QStringLiteral("Porcelain")
    << QStringLiteral("Parchment")
    << QStringLiteral("Rice")
    << QStringLiteral("Tan")
    << QStringLiteral("Beige")
    << QStringLiteral("Macaroon")
    << QStringLiteral("Hazelwood")
    << QStringLiteral("Granola")
    << QStringLiteral("Oat")
    << QStringLiteral("Eggnog")
    << QStringLiteral("Fawn")
    << QStringLiteral("Sand")
    << QStringLiteral("Sepia")
    << QStringLiteral("Ltte")
    << QStringLiteral("Oyster")
    << QStringLiteral("Biscotti")
    << QStringLiteral("Parmesan")
    << QStringLiteral("Hazelnut")
    << QStringLiteral("Sandcastle")
    << QStringLiteral("Buttermilk")
    << QStringLiteral("Shortbread")
    << QStringLiteral("Yellow")
    << QStringLiteral("Canary")
    << QStringLiteral("Gold")
    << QStringLiteral("Daffodil")
    << QStringLiteral("Flaxen")
    << QStringLiteral("Butter")
    << QStringLiteral("Lemon")
    << QStringLiteral("Mustard")
    << QStringLiteral("Corn")
    << QStringLiteral("Medallion")
    << QStringLiteral("Dandelion")
    << QStringLiteral("Fire")
    << QStringLiteral("Bumblebee")
    << QStringLiteral("Banana")
    << QStringLiteral("Butterscotch")
    << QStringLiteral("Dijon")
    << QStringLiteral("Honey")
    << QStringLiteral("Blonde")
    << QStringLiteral("Pineapple")
    << QStringLiteral("Orange")
    << QStringLiteral("Tangerine")
    << QStringLiteral("Marigold")
    << QStringLiteral("Cider")
    << QStringLiteral("Rust")
    << QStringLiteral("Ginger")
    << QStringLiteral("Tiger")
    << QStringLiteral("Fire")
    << QStringLiteral("Bronze")
    << QStringLiteral("Cantaloupe")
    << QStringLiteral("Apricot")
    << QStringLiteral("Clay")
    << QStringLiteral("Honey")
    << QStringLiteral("Carrot")
    << QStringLiteral("Squash")
    << QStringLiteral("Spice")
    << QStringLiteral("Marmalade")
    << QStringLiteral("Amber")
    << QStringLiteral("Sandstone")
    << QStringLiteral("Yam")
    << QStringLiteral("Red")
    << QStringLiteral("Cherry")
    << QStringLiteral("Rose")
    << QStringLiteral("Jam")
    << QStringLiteral("Merlot")
    << QStringLiteral("Garnet")
    << QStringLiteral("Crimson")
    << QStringLiteral("Ruby")
    << QStringLiteral("Scarlet")
    << QStringLiteral("Wine")
    << QStringLiteral("Brick")
    << QStringLiteral("Apple")
    << QStringLiteral("Mahogany")
    << QStringLiteral("Blood")
    << QStringLiteral("Sangria")
    << QStringLiteral("Berry")
    << QStringLiteral("Currant")
    << QStringLiteral("Blush")
    << QStringLiteral("Candy")
    << QStringLiteral("Lipstick")
    << QStringLiteral("Pink")
    << QStringLiteral("Rose")
    << QStringLiteral("Fuchsia")
    << QStringLiteral("Punch")
    << QStringLiteral("Blush")
    << QStringLiteral("Watermelon")
    << QStringLiteral("Flamingo")
    << QStringLiteral("Rouge")
    << QStringLiteral("Salmon")
    << QStringLiteral("Coral")
    << QStringLiteral("Peach")
    << QStringLiteral("Strawberry")
    << QStringLiteral("Rosewood")
    << QStringLiteral("Lemonade")
    << QStringLiteral("Taffy")
    << QStringLiteral("Bubblegum")
    << QStringLiteral("Crepe")
    << QStringLiteral("Magenta")
    << QStringLiteral("Purple")
    << QStringLiteral("Mauve")
    << QStringLiteral("Violet")
    << QStringLiteral("Boysenberry")
    << QStringLiteral("Lavender")
    << QStringLiteral("Plum")
    << QStringLiteral("Magenta")
    << QStringLiteral("Lilac")
    << QStringLiteral("Grape")
    << QStringLiteral("Periwinkle")
    << QStringLiteral("Sangria")
    << QStringLiteral("Eggplant")
    << QStringLiteral("Jam")
    << QStringLiteral("Iris")
    << QStringLiteral("Heather")
    << QStringLiteral("Amethyst")
    << QStringLiteral("Raisin")
    << QStringLiteral("Orchid")
    << QStringLiteral("Mulberry")
    << QStringLiteral("Wine")
    << QStringLiteral("Blue")
    << QStringLiteral("Slate")
    << QStringLiteral("Sky")
    << QStringLiteral("Navy")
    << QStringLiteral("Indigo")
    << QStringLiteral("Cobalt")
    << QStringLiteral("Teal")
    << QStringLiteral("Ocean")
    << QStringLiteral("Peacock")
    << QStringLiteral("Azure")
    << QStringLiteral("Cerulean")
    << QStringLiteral("Lapis")
    << QStringLiteral("Spruce")
    << QStringLiteral("Stone")
    << QStringLiteral("Aegean")
    << QStringLiteral("Berry")
    << QStringLiteral("Denim")
    << QStringLiteral("Admiral")
    << QStringLiteral("Sapphire")
    << QStringLiteral("Arctic")
    << QStringLiteral("Green")
    << QStringLiteral("Chartreuse")
    << QStringLiteral("Juniper")
    << QStringLiteral("Sage")
    << QStringLiteral("Lime")
    << QStringLiteral("Fern")
    << QStringLiteral("Olive")
    << QStringLiteral("Emerald")
    << QStringLiteral("Pear")
    << QStringLiteral("Moss")
    << QStringLiteral("Shamrock")
    << QStringLiteral("Seafoam")
    << QStringLiteral("Pine")
    << QStringLiteral("Parakeet")
    << QStringLiteral("Mint")
    << QStringLiteral("Seaweed")
    << QStringLiteral("Pickle")
    << QStringLiteral("Pistachio")
    << QStringLiteral("Basil")
    << QStringLiteral("Crocodile")
    << QStringLiteral("Brown")
    << QStringLiteral("Coffee")
    << QStringLiteral("Mocha")
    << QStringLiteral("Peanut")
    << QStringLiteral("Carob")
    << QStringLiteral("Hickory")
    << QStringLiteral("Wood")
    << QStringLiteral("Pecan")
    << QStringLiteral("Walnut")
    << QStringLiteral("Caramel")
    << QStringLiteral("Gingerbread")
    << QStringLiteral("Syrup")
    << QStringLiteral("Chocolate")
    << QStringLiteral("Tortilla")
    << QStringLiteral("Umber")
    << QStringLiteral("Tawny")
    << QStringLiteral("Brunette")
    << QStringLiteral("Cinnamon")
    << QStringLiteral("Penny")
    << QStringLiteral("Cedar")
    << QStringLiteral("Grey")
    << QStringLiteral("Shadow")
    << QStringLiteral("Graphite")
    << QStringLiteral("Iron")
    << QStringLiteral("Pewter")
    << QStringLiteral("Cloud")
    << QStringLiteral("Silver")
    << QStringLiteral("Smoke")
    << QStringLiteral("Slate")
    << QStringLiteral("Anchor")
    << QStringLiteral("Ash")
    << QStringLiteral("Porpoise")
    << QStringLiteral("Dove")
    << QStringLiteral("Fog")
    << QStringLiteral("Flint")
    << QStringLiteral("Charcoal")
    << QStringLiteral("Pebble")
    << QStringLiteral("Lead")
    << QStringLiteral("Coin")
    << QStringLiteral("Fossil")
    << QStringLiteral("Black")
    << QStringLiteral("Ebony")
    << QStringLiteral("Crow")
    << QStringLiteral("Charcoal")
    << QStringLiteral("Midnight")
    << QStringLiteral("Ink")
    << QStringLiteral("Raven")
    << QStringLiteral("Oil")
    << QStringLiteral("Grease")
    << QStringLiteral("Onyx")
    << QStringLiteral("Pitch")
    << QStringLiteral("Soot")
    << QStringLiteral("Sable")
    << QStringLiteral("Jet")
    << QStringLiteral("Coal")
    << QStringLiteral("Metal")
    << QStringLiteral("Obsidian")
    << QStringLiteral("Jade")
    << QStringLiteral("Spider")
    << QStringLiteral("Leather")
  ;
}


void CRandomizer::buildUSCityList() {
  _allUSCities
      << QStringLiteral("Abilene")
      << QStringLiteral("Addison")
      << QStringLiteral("Akron")
      << QStringLiteral("Alameda")
      << QStringLiteral("Albany")
      << QStringLiteral("Albuquerque")
      << QStringLiteral("Alexandria")
      << QStringLiteral("Alhambra")
      << QStringLiteral("Aliso Viejo")
      << QStringLiteral("Allen")
      << QStringLiteral("Allentown")
      << QStringLiteral("Alpharetta")
      << QStringLiteral("Altamonte Springs")
      << QStringLiteral("Altoona")
      << QStringLiteral("Amarillo")
      << QStringLiteral("Ames")
      << QStringLiteral("Anaheim")
      << QStringLiteral("Anchorage")
      << QStringLiteral("Anderson")
      << QStringLiteral("Ankeny")
      << QStringLiteral("Ann Arbor")
      << QStringLiteral("Annapolis")
      << QStringLiteral("Antioch")
      << QStringLiteral("Apache Junction")
      << QStringLiteral("Apex")
      << QStringLiteral("Apopka")
      << QStringLiteral("Apple Valley")
      << QStringLiteral("Appleton")
      << QStringLiteral("Arcadia")
      << QStringLiteral("Arlington")
      << QStringLiteral("Arlington Heights")
      << QStringLiteral("Arvada")
      << QStringLiteral("Asheville")
      << QStringLiteral("Athens")
      << QStringLiteral("Atlanta")
      << QStringLiteral("Atlantic City")
      << QStringLiteral("Attleboro")
      << QStringLiteral("Auburn")
      << QStringLiteral("Augusta")
      << QStringLiteral("Aurora")
      << QStringLiteral("Austin")
      << QStringLiteral("Aventura")
      << QStringLiteral("Avondale")
      << QStringLiteral("Azusa")
      << QStringLiteral("Bakersfield")
      << QStringLiteral("Baldwin Park")
      << QStringLiteral("Baltimore")
      << QStringLiteral("Barnstable Town")
      << QStringLiteral("Bartlett")
      << QStringLiteral("Baton Rouge")
      << QStringLiteral("Battle Creek")
      << QStringLiteral("Bayonne")
      << QStringLiteral("Baytown")
      << QStringLiteral("Beaumont")
      << QStringLiteral("Beavercreek")
      << QStringLiteral("Beaverton")
      << QStringLiteral("Bedford")
      << QStringLiteral("Bell Gardens")
      << QStringLiteral("Belleville")
      << QStringLiteral("Bellevue")
      << QStringLiteral("Bellflower")
      << QStringLiteral("Bellingham")
      << QStringLiteral("Beloit")
      << QStringLiteral("Bend")
      << QStringLiteral("Bentonville")
      << QStringLiteral("Berkeley")
      << QStringLiteral("Berwyn")
      << QStringLiteral("Bethlehem")
      << QStringLiteral("Beverly")
      << QStringLiteral("Billings")
      << QStringLiteral("Biloxi")
      << QStringLiteral("Binghamton")
      << QStringLiteral("Birmingham")
      << QStringLiteral("Bismarck")
      << QStringLiteral("Blacksburg")
      << QStringLiteral("Blaine")
      << QStringLiteral("Bloomington")
      << QStringLiteral("Blue Springs")
      << QStringLiteral("Boca Raton")
      << QStringLiteral("Boise City")
      << QStringLiteral("Bolingbrook")
      << QStringLiteral("Bonita Springs")
      << QStringLiteral("Bossier City")
      << QStringLiteral("Boston")
      << QStringLiteral("Boulder")
      << QStringLiteral("Bountiful")
      << QStringLiteral("Bowie")
      << QStringLiteral("Bowling Green")
      << QStringLiteral("Boynton Beach")
      << QStringLiteral("Bozeman")
      << QStringLiteral("Bradenton")
      << QStringLiteral("Brea")
      << QStringLiteral("Bremerton")
      << QStringLiteral("Brentwood")
      << QStringLiteral("Bridgeport")
      << QStringLiteral("Bristol")
      << QStringLiteral("Brockton")
      << QStringLiteral("Broken Arrow")
      << QStringLiteral("Brookfield")
      << QStringLiteral("Brookhaven")
      << QStringLiteral("Brooklyn Park")
      << QStringLiteral("Broomfield")
      << QStringLiteral("Brownsville")
      << QStringLiteral("Bryan")
      << QStringLiteral("Buckeye")
      << QStringLiteral("Buena Park")
      << QStringLiteral("Buffalo")
      << QStringLiteral("Buffalo Grove")
      << QStringLiteral("Bullhead City")
      << QStringLiteral("Burbank")
      << QStringLiteral("Burien")
      << QStringLiteral("Burleson")
      << QStringLiteral("Burlington")
      << QStringLiteral("Burnsville")
      << QStringLiteral("Caldwell")
      << QStringLiteral("Calexico")
      << QStringLiteral("Calumet City")
      << QStringLiteral("Camarillo")
      << QStringLiteral("Cambridge")
      << QStringLiteral("Camden")
      << QStringLiteral("Campbell")
      << QStringLiteral("Canton")
      << QStringLiteral("Cape Coral")
      << QStringLiteral("Cape Girardeau")
      << QStringLiteral("Carlsbad")
      << QStringLiteral("Carmel")
      << QStringLiteral("Carol Stream")
      << QStringLiteral("Carpentersville")
      << QStringLiteral("Carrollton")
      << QStringLiteral("Carson")
      << QStringLiteral("Carson City")
      << QStringLiteral("Cary")
      << QStringLiteral("Casa Grande")
      << QStringLiteral("Casper")
      << QStringLiteral("Castle Rock")
      << QStringLiteral("Cathedral City")
      << QStringLiteral("Cedar Falls")
      << QStringLiteral("Cedar Hill")
      << QStringLiteral("Cedar Park")
      << QStringLiteral("Cedar Rapids")
      << QStringLiteral("Centennial")
      << QStringLiteral("Ceres")
      << QStringLiteral("Cerritos")
      << QStringLiteral("Champaign")
      << QStringLiteral("Chandler")
      << QStringLiteral("Chapel Hill")
      << QStringLiteral("Charleston")
      << QStringLiteral("Charlotte")
      << QStringLiteral("Charlottesville")
      << QStringLiteral("Chattanooga")
      << QStringLiteral("Chelsea")
      << QStringLiteral("Chesapeake")
      << QStringLiteral("Chesterfield")
      << QStringLiteral("Cheyenne")
      << QStringLiteral("Chicago")
      << QStringLiteral("Chico")
      << QStringLiteral("Chicopee")
      << QStringLiteral("Chino")
      << QStringLiteral("Chino Hills")
      << QStringLiteral("Chula Vista")
      << QStringLiteral("Cicero")
      << QStringLiteral("Cincinnati")
      << QStringLiteral("Citrus Heights")
      << QStringLiteral("Clarksville")
      << QStringLiteral("Clearwater")
      << QStringLiteral("Cleveland")
      << QStringLiteral("Cleveland Heights")
      << QStringLiteral("Clifton")
      << QStringLiteral("Clovis")
      << QStringLiteral("Coachella")
      << QStringLiteral("Coconut Creek")
      << QStringLiteral("Coeur d'Alene")
      << QStringLiteral("College Station")
      << QStringLiteral("Collierville")
      << QStringLiteral("Colorado Springs")
      << QStringLiteral("Colton")
      << QStringLiteral("Columbia")
      << QStringLiteral("Columbus")
      << QStringLiteral("Commerce City")
      << QStringLiteral("Compton")
      << QStringLiteral("Concord")
      << QStringLiteral("Conroe")
      << QStringLiteral("Conway")
      << QStringLiteral("Coon Rapids")
      << QStringLiteral("Coppell")
      << QStringLiteral("Coral Gables")
      << QStringLiteral("Coral Springs")
      << QStringLiteral("Corona")
      << QStringLiteral("Corpus Christi")
      << QStringLiteral("Corvallis")
      << QStringLiteral("Costa Mesa")
      << QStringLiteral("Council Bluffs")
      << QStringLiteral("Covina")
      << QStringLiteral("Covington")
      << QStringLiteral("Cranston")
      << QStringLiteral("Crystal Lake")
      << QStringLiteral("Culver City")
      << QStringLiteral("Cupertino")
      << QStringLiteral("Cutler Bay")
      << QStringLiteral("Cuyahoga Falls")
      << QStringLiteral("Cypress")
      << QStringLiteral("Dallas")
      << QStringLiteral("Daly City")
      << QStringLiteral("Danbury")
      << QStringLiteral("Danville")
      << QStringLiteral("Davenport")
      << QStringLiteral("Davie")
      << QStringLiteral("Davis")
      << QStringLiteral("Dayton")
      << QStringLiteral("Daytona Beach")
      << QStringLiteral("Dearborn")
      << QStringLiteral("Dearborn Heights")
      << QStringLiteral("Decatur")
      << QStringLiteral("Deerfield Beach")
      << QStringLiteral("DeKalb")
      << QStringLiteral("Delano")
      << QStringLiteral("Delray Beach")
      << QStringLiteral("Deltona")
      << QStringLiteral("Denton")
      << QStringLiteral("Denver")
      << QStringLiteral("Des Moines")
      << QStringLiteral("Des Plaines")
      << QStringLiteral("DeSoto")
      << QStringLiteral("Detroit")
      << QStringLiteral("Diamond Bar")
      << QStringLiteral("Doral")
      << QStringLiteral("Dothan")
      << QStringLiteral("Dover")
      << QStringLiteral("Downers Grove")
      << QStringLiteral("Downey")
      << QStringLiteral("Draper")
      << QStringLiteral("Dublin")
      << QStringLiteral("Dubuque")
      << QStringLiteral("Duluth")
      << QStringLiteral("Duncanville")
      << QStringLiteral("Dunwoody")
      << QStringLiteral("Durham")
      << QStringLiteral("Eagan")
      << QStringLiteral("Eastvale")
      << QStringLiteral("Eau Claire")
      << QStringLiteral("Eden Prairie")
      << QStringLiteral("Edina")
      << QStringLiteral("Edinburg")
      << QStringLiteral("Edmond")
      << QStringLiteral("Edmonds")
      << QStringLiteral("El Cajon")
      << QStringLiteral("El Centro")
      << QStringLiteral("El Monte")
      << QStringLiteral("El Paso")
      << QStringLiteral("Elgin")
      << QStringLiteral("Elizabeth")
      << QStringLiteral("Elk Grove")
      << QStringLiteral("Elkhart")
      << QStringLiteral("Elmhurst")
      << QStringLiteral("Elyria")
      << QStringLiteral("Encinitas")
      << QStringLiteral("Enid")
      << QStringLiteral("Erie")
      << QStringLiteral("Escondido")
      << QStringLiteral("Euclid")
      << QStringLiteral("Eugene")
      << QStringLiteral("Euless")
      << QStringLiteral("Evanston")
      << QStringLiteral("Evansville")
      << QStringLiteral("Everett")
      << QStringLiteral("Fairfield")
      << QStringLiteral("Fall River")
      << QStringLiteral("Fargo")
      << QStringLiteral("Farmington")
      << QStringLiteral("Farmington Hills")
      << QStringLiteral("Fayetteville")
      << QStringLiteral("Federal Way")
      << QStringLiteral("Findlay")
      << QStringLiteral("Fishers")
      << QStringLiteral("Fitchburg")
      << QStringLiteral("Flagstaff")
      << QStringLiteral("Flint")
      << QStringLiteral("Florence")
      << QStringLiteral("Florissant")
      << QStringLiteral("Flower Mound")
      << QStringLiteral("Folsom")
      << QStringLiteral("Fond du Lac")
      << QStringLiteral("Fontana")
      << QStringLiteral("Fort Collins")
      << QStringLiteral("Fort Lauderdale")
      << QStringLiteral("Fort Myers")
      << QStringLiteral("Fort Pierce")
      << QStringLiteral("Fort Smith")
      << QStringLiteral("Fort Wayne")
      << QStringLiteral("Fort Worth")
      << QStringLiteral("Fountain Valley")
      << QStringLiteral("Franklin")
      << QStringLiteral("Frederick")
      << QStringLiteral("Freeport")
      << QStringLiteral("Fremont")
      << QStringLiteral("Fresno")
      << QStringLiteral("Friendswood")
      << QStringLiteral("Frisco")
      << QStringLiteral("Fullerton")
      << QStringLiteral("Gainesville")
      << QStringLiteral("Gaithersburg")
      << QStringLiteral("Galveston")
      << QStringLiteral("Garden Grove")
      << QStringLiteral("Gardena")
      << QStringLiteral("Garland")
      << QStringLiteral("Gary")
      << QStringLiteral("Gastonia")
      << QStringLiteral("Georgetown")
      << QStringLiteral("Germantown")
      << QStringLiteral("Gilbert")
      << QStringLiteral("Gilroy")
      << QStringLiteral("Glendale")
      << QStringLiteral("Glendora")
      << QStringLiteral("Glenview")
      << QStringLiteral("Goodyear")
      << QStringLiteral("Goose Creek")
      << QStringLiteral("Grand Forks")
      << QStringLiteral("Grand Island")
      << QStringLiteral("Grand Junction")
      << QStringLiteral("Grand Prairie")
      << QStringLiteral("Grand Rapids")
      << QStringLiteral("Grapevine")
      << QStringLiteral("Great Falls")
      << QStringLiteral("Greeley")
      << QStringLiteral("Green Bay")
      << QStringLiteral("Greenacres")
      << QStringLiteral("Greenfield")
      << QStringLiteral("Greensboro")
      << QStringLiteral("Greenville")
      << QStringLiteral("Greenwood")
      << QStringLiteral("Gresham")
      << QStringLiteral("Grove City")
      << QStringLiteral("Gulfport")
      << QStringLiteral("Hackensack")
      << QStringLiteral("Hagerstown")
      << QStringLiteral("Hallandale Beach")
      << QStringLiteral("Haltom City")
      << QStringLiteral("Hamilton")
      << QStringLiteral("Hammond")
      << QStringLiteral("Hampton")
      << QStringLiteral("Hanford")
      << QStringLiteral("Hanover Park")
      << QStringLiteral("Harlingen")
      << QStringLiteral("Harrisburg")
      << QStringLiteral("Harrisonburg")
      << QStringLiteral("Hartford")
      << QStringLiteral("Hattiesburg")
      << QStringLiteral("Haverhill")
      << QStringLiteral("Hawthorne")
      << QStringLiteral("Hayward")
      << QStringLiteral("Hemet")
      << QStringLiteral("Hempstead")
      << QStringLiteral("Henderson")
      << QStringLiteral("Hendersonville")
      << QStringLiteral("Hesperia")
      << QStringLiteral("Hialeah")
      << QStringLiteral("Hickory")
      << QStringLiteral("High Point")
      << QStringLiteral("Highland")
      << QStringLiteral("Hillsboro")
      << QStringLiteral("Hilton Head Island")
      << QStringLiteral("Hoboken")
      << QStringLiteral("Hoffman Estates")
      << QStringLiteral("Hollywood")
      << QStringLiteral("Holyoke")
      << QStringLiteral("Homestead")
      << QStringLiteral("Honolulu")
      << QStringLiteral("Hoover")
      << QStringLiteral("Houston")
      << QStringLiteral("Huber Heights")
      << QStringLiteral("Huntersville")
      << QStringLiteral("Huntington")
      << QStringLiteral("Huntington Beach")
      << QStringLiteral("Huntington Park")
      << QStringLiteral("Huntsville")
      << QStringLiteral("Hurst")
      << QStringLiteral("Hutchinson")
      << QStringLiteral("Idaho Falls")
      << QStringLiteral("Independence")
      << QStringLiteral("Indianapolis")
      << QStringLiteral("Indio")
      << QStringLiteral("Inglewood")
      << QStringLiteral("Iowa City")
      << QStringLiteral("Irvine")
      << QStringLiteral("Irving")
      << QStringLiteral("Jackson")
      << QStringLiteral("Jacksonville")
      << QStringLiteral("Janesville")
      << QStringLiteral("Jefferson City")
      << QStringLiteral("Jeffersonville")
      << QStringLiteral("Jersey City")
      << QStringLiteral("Johns Creek")
      << QStringLiteral("Johnson City")
      << QStringLiteral("Joliet")
      << QStringLiteral("Jonesboro")
      << QStringLiteral("Joplin")
      << QStringLiteral("Jordan")
      << QStringLiteral("Jupiter")
      << QStringLiteral("Jurupa Valley")
      << QStringLiteral("Kalamazoo")
      << QStringLiteral("Kannapolis")
      << QStringLiteral("Kansas City")
      << QStringLiteral("Kearny")
      << QStringLiteral("Keizer")
      << QStringLiteral("Keller")
      << QStringLiteral("Kenner")
      << QStringLiteral("Kennewick")
      << QStringLiteral("Kenosha")
      << QStringLiteral("Kent")
      << QStringLiteral("Kentwood")
      << QStringLiteral("Kettering")
      << QStringLiteral("Killeen")
      << QStringLiteral("Kingsport")
      << QStringLiteral("Kirkland")
      << QStringLiteral("Kissimmee")
      << QStringLiteral("Knoxville")
      << QStringLiteral("Kokomo")
      << QStringLiteral("La Crosse")
      << QStringLiteral("La Habra")
      << QStringLiteral("La Mesa")
      << QStringLiteral("La Mirada")
      << QStringLiteral("La Puente")
      << QStringLiteral("La Quinta")
      << QStringLiteral("Lacey")
      << QStringLiteral("Lafayette")
      << QStringLiteral("Laguna Niguel")
      << QStringLiteral("Lake Charles")
      << QStringLiteral("Lake Elsinore")
      << QStringLiteral("Lake Forest")
      << QStringLiteral("Lake Havasu City")
      << QStringLiteral("Lake Oswego")
      << QStringLiteral("Lakeland")
      << QStringLiteral("Lakeville")
      << QStringLiteral("Lakewood")
      << QStringLiteral("Lancaster")
      << QStringLiteral("Lansing")
      << QStringLiteral("Laredo")
      << QStringLiteral("Largo")
      << QStringLiteral("Las Cruces")
      << QStringLiteral("Las Vegas")
      << QStringLiteral("Lauderhill")
      << QStringLiteral("Lawrence")
      << QStringLiteral("Lawton")
      << QStringLiteral("Layton")
      << QStringLiteral("League City")
      << QStringLiteral("Lee's Summit")
      << QStringLiteral("Leesburg")
      << QStringLiteral("Lehi")
      << QStringLiteral("Lenexa")
      << QStringLiteral("Leominster")
      << QStringLiteral("Lewisville")
      << QStringLiteral("Lexington")
      << QStringLiteral("Lima")
      << QStringLiteral("Lincoln")
      << QStringLiteral("Lincoln Park")
      << QStringLiteral("Linden")
      << QStringLiteral("Little Rock")
      << QStringLiteral("Littleton")
      << QStringLiteral("Livermore")
      << QStringLiteral("Livonia")
      << QStringLiteral("Lodi")
      << QStringLiteral("Logan")
      << QStringLiteral("Lombard")
      << QStringLiteral("Lompoc")
      << QStringLiteral("Long Beach")
      << QStringLiteral("Longmont")
      << QStringLiteral("Longview")
      << QStringLiteral("Lorain")
      << QStringLiteral("Los Angeles")
      << QStringLiteral("Louisville")
      << QStringLiteral("Loveland")
      << QStringLiteral("Lowell")
      << QStringLiteral("Lubbock")
      << QStringLiteral("Lynchburg")
      << QStringLiteral("Lynn")
      << QStringLiteral("Lynwood")
      << QStringLiteral("Macon")
      << QStringLiteral("Madera")
      << QStringLiteral("Madison")
      << QStringLiteral("Malden")
      << QStringLiteral("Manassas")
      << QStringLiteral("Manchester")
      << QStringLiteral("Manhattan")
      << QStringLiteral("Mankato")
      << QStringLiteral("Mansfield")
      << QStringLiteral("Manteca")
      << QStringLiteral("Maple Grove")
      << QStringLiteral("Maplewood")
      << QStringLiteral("Marana")
      << QStringLiteral("Margate")
      << QStringLiteral("Maricopa")
      << QStringLiteral("Marietta")
      << QStringLiteral("Marlborough")
      << QStringLiteral("Martinez")
      << QStringLiteral("Marysville")
      << QStringLiteral("McAllen")
      << QStringLiteral("McKinney")
      << QStringLiteral("Medford")
      << QStringLiteral("Melbourne")
      << QStringLiteral("Memphis")
      << QStringLiteral("Menifee")
      << QStringLiteral("Mentor")
      << QStringLiteral("Merced")
      << QStringLiteral("Meriden")
      << QStringLiteral("Meridian")
      << QStringLiteral("Mesa")
      << QStringLiteral("Mesquite")
      << QStringLiteral("Methuen")
      << QStringLiteral("Miami")
      << QStringLiteral("Miami Beach")
      << QStringLiteral("Miami Gardens")
      << QStringLiteral("Middletown")
      << QStringLiteral("Midland")
      << QStringLiteral("Midwest City")
      << QStringLiteral("Milford")
      << QStringLiteral("Milpitas")
      << QStringLiteral("Milwaukee")
      << QStringLiteral("Minneapolis")
      << QStringLiteral("Minnetonka")
      << QStringLiteral("Minot")
      << QStringLiteral("Miramar")
      << QStringLiteral("Mishawaka")
      << QStringLiteral("Mission")
      << QStringLiteral("Mission Viejo")
      << QStringLiteral("Missoula")
      << QStringLiteral("Missouri City")
      << QStringLiteral("Mobile")
      << QStringLiteral("Modesto")
      << QStringLiteral("Moline")
      << QStringLiteral("Monroe")
      << QStringLiteral("Monrovia")
      << QStringLiteral("Montclair")
      << QStringLiteral("Montebello")
      << QStringLiteral("Monterey Park")
      << QStringLiteral("Montgomery")
      << QStringLiteral("Moore")
      << QStringLiteral("Moorhead")
      << QStringLiteral("Moreno Valley")
      << QStringLiteral("Morgan Hill")
      << QStringLiteral("Mount Pleasant")
      << QStringLiteral("Mount Prospect")
      << QStringLiteral("Mount Vernon")
      << QStringLiteral("Mountain View")
      << QStringLiteral("Muncie")
      << QStringLiteral("Murfreesboro")
      << QStringLiteral("Murray")
      << QStringLiteral("Murrieta")
      << QStringLiteral("Muskegon")
      << QStringLiteral("Muskogee")
      << QStringLiteral("Nampa")
      << QStringLiteral("Napa")
      << QStringLiteral("Naperville")
      << QStringLiteral("Nashua")
      << QStringLiteral("Nashville-Davidson")
      << QStringLiteral("National City")
      << QStringLiteral("New Bedford")
      << QStringLiteral("New Berlin")
      << QStringLiteral("New Braunfels")
      << QStringLiteral("New Britain")
      << QStringLiteral("New Brunswick")
      << QStringLiteral("New Haven")
      << QStringLiteral("New Orleans")
      << QStringLiteral("New Rochelle")
      << QStringLiteral("New York")
      << QStringLiteral("Newark")
      << QStringLiteral("Newport Beach")
      << QStringLiteral("Newport News")
      << QStringLiteral("Newton")
      << QStringLiteral("Niagara Falls")
      << QStringLiteral("Noblesville")
      << QStringLiteral("Norfolk")
      << QStringLiteral("Normal")
      << QStringLiteral("Norman")
      << QStringLiteral("North Port")
      << QStringLiteral("Northglenn")
      << QStringLiteral("Norwalk")
      << QStringLiteral("Norwich")
      << QStringLiteral("Novato")
      << QStringLiteral("Novi")
      << QStringLiteral("Oak Lawn")
      << QStringLiteral("Oak Park")
      << QStringLiteral("Oakland")
      << QStringLiteral("Oakland Park")
      << QStringLiteral("Oakley")
      << QStringLiteral("Ocala")
      << QStringLiteral("Oceanside")
      << QStringLiteral("Ocoee")
      << QStringLiteral("Odessa")
      << QStringLiteral("O'Fallon")
      << QStringLiteral("Ogden")
      << QStringLiteral("Oklahoma City")
      << QStringLiteral("Olathe")
      << QStringLiteral("Olympia")
      << QStringLiteral("Omaha")
      << QStringLiteral("Ontario")
      << QStringLiteral("Orange")
      << QStringLiteral("Orem")
      << QStringLiteral("Orland Park")
      << QStringLiteral("Orlando")
      << QStringLiteral("Ormond Beach")
      << QStringLiteral("Oro Valley")
      << QStringLiteral("Oshkosh")
      << QStringLiteral("Overland Park")
      << QStringLiteral("Owensboro")
      << QStringLiteral("Oxnard")
      << QStringLiteral("Pacifica")
      << QStringLiteral("Palatine")
      << QStringLiteral("Palm Bay")
      << QStringLiteral("Palm Beach")
      << QStringLiteral("Palm Coast")
      << QStringLiteral("Palm Desert")
      << QStringLiteral("Palm Springs")
      << QStringLiteral("Palmdale")
      << QStringLiteral("Palo Alto")
      << QStringLiteral("Panama City")
      << QStringLiteral("Paramount")
      << QStringLiteral("Park Ridge")
      << QStringLiteral("Parker")
      << QStringLiteral("Parma")
      << QStringLiteral("Pasadena")
      << QStringLiteral("Pasco")
      << QStringLiteral("Passaic")
      << QStringLiteral("Paterson")
      << QStringLiteral("Pawtucket")
      << QStringLiteral("Peabody")
      << QStringLiteral("Peachtree Corners")
      << QStringLiteral("Pearland")
      << QStringLiteral("Pembroke Pines")
      << QStringLiteral("Pensacola")
      << QStringLiteral("Peoria")
      << QStringLiteral("Perris")
      << QStringLiteral("Perth Amboy")
      << QStringLiteral("Petaluma")
      << QStringLiteral("Pflugerville")
      << QStringLiteral("Pharr")
      << QStringLiteral("Phenix City")
      << QStringLiteral("Philadelphia")
      << QStringLiteral("Phoenix")
      << QStringLiteral("Pico Rivera")
      << QStringLiteral("Pine Bluff")
      << QStringLiteral("Pinellas Park")
      << QStringLiteral("Pittsburg")
      << QStringLiteral("Pittsburgh")
      << QStringLiteral("Pittsfield")
      << QStringLiteral("Placentia")
      << QStringLiteral("Plainfield")
      << QStringLiteral("Plano")
      << QStringLiteral("Plantation")
      << QStringLiteral("Pleasanton")
      << QStringLiteral("Plymouth")
      << QStringLiteral("Pocatello")
      << QStringLiteral("Pomona")
      << QStringLiteral("Pompano Beach")
      << QStringLiteral("Pontiac")
      << QStringLiteral("Port Arthur")
      << QStringLiteral("Port Orange")
      << QStringLiteral("Port St. Lucie")
      << QStringLiteral("Portage")
      << QStringLiteral("Porterville")
      << QStringLiteral("Portland")
      << QStringLiteral("Portsmouth")
      << QStringLiteral("Poway")
      << QStringLiteral("Prescott")
      << QStringLiteral("Prescott Valley")
      << QStringLiteral("Providence")
      << QStringLiteral("Provo")
      << QStringLiteral("Pueblo")
      << QStringLiteral("Puyallup")
      << QStringLiteral("Quincy")
      << QStringLiteral("Racine")
      << QStringLiteral("Raleigh")
      << QStringLiteral("Rancho Cordova")
      << QStringLiteral("Rancho Cucamonga")
      << QStringLiteral("Rancho Palos Verdes")
      << QStringLiteral("Rancho Santa Margarita")
      << QStringLiteral("Rapid City")
      << QStringLiteral("Reading")
      << QStringLiteral("Redding")
      << QStringLiteral("Redlands")
      << QStringLiteral("Redmond")
      << QStringLiteral("Redondo Beach")
      << QStringLiteral("Redwood City")
      << QStringLiteral("Reno")
      << QStringLiteral("Renton")
      << QStringLiteral("Revere")
      << QStringLiteral("Rialto")
      << QStringLiteral("Richardson")
      << QStringLiteral("Richland")
      << QStringLiteral("Richland Hills")
      << QStringLiteral("Richmond")
      << QStringLiteral("Rio Rancho")
      << QStringLiteral("Riverside")
      << QStringLiteral("Riverton")
      << QStringLiteral("Roanoke")
      << QStringLiteral("Rochester")
      << QStringLiteral("Rochester Hills")
      << QStringLiteral("Rock Hill")
      << QStringLiteral("Rock Island")
      << QStringLiteral("Rockford")
      << QStringLiteral("Rocklin")
      << QStringLiteral("Rockville")
      << QStringLiteral("Rockwall")
      << QStringLiteral("Rocky Mount")
      << QStringLiteral("Rogers")
      << QStringLiteral("Rohnert Park")
      << QStringLiteral("Romeoville")
      << QStringLiteral("Rosemead")
      << QStringLiteral("Roseville")
      << QStringLiteral("Roswell")
      << QStringLiteral("Round Rock")
      << QStringLiteral("Rowlett")
      << QStringLiteral("Roy")
      << QStringLiteral("Royal Oak")
      << QStringLiteral("Sacramento")
      << QStringLiteral("Saginaw")
      << QStringLiteral("Salem")
      << QStringLiteral("Salina")
      << QStringLiteral("Salinas")
      << QStringLiteral("Salt Lake City")
      << QStringLiteral("Sammamish")
      << QStringLiteral("San Angelo")
      << QStringLiteral("San Antonio")
      << QStringLiteral("San Bernardino")
      << QStringLiteral("San Bruno")
      << QStringLiteral("San Buenaventura")
      << QStringLiteral("San Clemente")
      << QStringLiteral("San Diego")
      << QStringLiteral("San Francisco")
      << QStringLiteral("San Gabriel")
      << QStringLiteral("San Jacinto")
      << QStringLiteral("San Jose")
      << QStringLiteral("San Leandro")
      << QStringLiteral("San Luis Obispo")
      << QStringLiteral("San Marcos")
      << QStringLiteral("San Mateo")
      << QStringLiteral("San Rafael")
      << QStringLiteral("San Ramon")
      << QStringLiteral("Sandy")
      << QStringLiteral("Sandy Springs")
      << QStringLiteral("Sanford")
      << QStringLiteral("Santa Ana")
      << QStringLiteral("Santa Barbara")
      << QStringLiteral("Santa Clara")
      << QStringLiteral("Santa Clarita")
      << QStringLiteral("Santa Cruz")
      << QStringLiteral("Santa Fe")
      << QStringLiteral("Santa Maria")
      << QStringLiteral("Santa Monica")
      << QStringLiteral("Santa Rosa")
      << QStringLiteral("Santee")
      << QStringLiteral("Sarasota")
      << QStringLiteral("Savannah")
      << QStringLiteral("Sayreville")
      << QStringLiteral("Schaumburg")
      << QStringLiteral("Schenectady")
      << QStringLiteral("Scottsdale")
      << QStringLiteral("Scranton")
      << QStringLiteral("Seattle")
      << QStringLiteral("Shakopee")
      << QStringLiteral("Shawnee")
      << QStringLiteral("Sheboygan")
      << QStringLiteral("Shelton")
      << QStringLiteral("Sherman")
      << QStringLiteral("Shoreline")
      << QStringLiteral("Shreveport")
      << QStringLiteral("Sierra Vista")
      << QStringLiteral("Simi Valley")
      << QStringLiteral("Sioux City")
      << QStringLiteral("Sioux Falls")
      << QStringLiteral("Skokie")
      << QStringLiteral("Smyrna")
      << QStringLiteral("Somerville")
      << QStringLiteral("South Bend")
      << QStringLiteral("South Gate")
      << QStringLiteral("Southaven")
      << QStringLiteral("Southfield")
      << QStringLiteral("Spanish Fork")
      << QStringLiteral("Sparks")
      << QStringLiteral("Spartanburg")
      << QStringLiteral("Spokane")
      << QStringLiteral("Spokane Valley")
      << QStringLiteral("Springdale")
      << QStringLiteral("Springfield")
      << QStringLiteral("St. Charles")
      << QStringLiteral("St. Clair Shores")
      << QStringLiteral("St. Cloud")
      << QStringLiteral("St. George")
      << QStringLiteral("St. Joseph")
      << QStringLiteral("St. Louis")
      << QStringLiteral("St. Louis Park")
      << QStringLiteral("St. Paul")
      << QStringLiteral("St. Peters")
      << QStringLiteral("St. Petersburg")
      << QStringLiteral("Stamford")
      << QStringLiteral("Stanton")
      << QStringLiteral("State College")
      << QStringLiteral("Sterling Heights")
      << QStringLiteral("Stillwater")
      << QStringLiteral("Stockton")
      << QStringLiteral("Streamwood")
      << QStringLiteral("Strongsville")
      << QStringLiteral("Suffolk")
      << QStringLiteral("Sugar Land")
      << QStringLiteral("Summerville")
      << QStringLiteral("Sumter")
      << QStringLiteral("Sunnyvale")
      << QStringLiteral("Sunrise")
      << QStringLiteral("Surprise")
      << QStringLiteral("Syracuse")
      << QStringLiteral("Tacoma")
      << QStringLiteral("Tallahassee")
      << QStringLiteral("Tamarac")
      << QStringLiteral("Tampa")
      << QStringLiteral("Taunton")
      << QStringLiteral("Taylor")
      << QStringLiteral("Taylorsville")
      << QStringLiteral("Temecula")
      << QStringLiteral("Tempe")
      << QStringLiteral("Temple")
      << QStringLiteral("Terre Haute")
      << QStringLiteral("Texarkana")
      << QStringLiteral("Texas City")
      << QStringLiteral("The Colony")
      << QStringLiteral("Thornton")
      << QStringLiteral("Thousand Oaks")
      << QStringLiteral("Tigard")
      << QStringLiteral("Tinley Park")
      << QStringLiteral("Titusville")
      << QStringLiteral("Toledo")
      << QStringLiteral("Topeka")
      << QStringLiteral("Torrance")
      << QStringLiteral("Tracy")
      << QStringLiteral("Trenton")
      << QStringLiteral("Troy")
      << QStringLiteral("Tucson")
      << QStringLiteral("Tulare")
      << QStringLiteral("Tulsa")
      << QStringLiteral("Turlock")
      << QStringLiteral("Tuscaloosa")
      << QStringLiteral("Tustin")
      << QStringLiteral("Twin Falls")
      << QStringLiteral("Tyler")
      << QStringLiteral("Union City")
      << QStringLiteral("Upland")
      << QStringLiteral("Urbana")
      << QStringLiteral("Urbandale")
      << QStringLiteral("Utica")
      << QStringLiteral("Vacaville")
      << QStringLiteral("Valdosta")
      << QStringLiteral("Vallejo")
      << QStringLiteral("Valley City")
      << QStringLiteral("Valley Stream")
      << QStringLiteral("Vancouver")
      << QStringLiteral("Victoria")
      << QStringLiteral("Victorville")
      << QStringLiteral("Vineland")
      << QStringLiteral("Virginia Beach")
      << QStringLiteral("Visalia")
      << QStringLiteral("Vista")
      << QStringLiteral("Waco")
      << QStringLiteral("Walnut Creek")
      << QStringLiteral("Waltham")
      << QStringLiteral("Warner Robins")
      << QStringLiteral("Warren")
      << QStringLiteral("Warwick")
      << QStringLiteral("Washington")
      << QStringLiteral("Waterbury")
      << QStringLiteral("Waterloo")
      << QStringLiteral("Watsonville")
      << QStringLiteral("Waukegan")
      << QStringLiteral("Waukesha")
      << QStringLiteral("Wausau")
      << QStringLiteral("Wauwatosa")
      << QStringLiteral("Wellington")
      << QStringLiteral("Weslaco")
      << QStringLiteral("West Allis")
      << QStringLiteral("West Haven")
      << QStringLiteral("West Sacramento")
      << QStringLiteral("Westerville")
      << QStringLiteral("Westfield")
      << QStringLiteral("Westland")
      << QStringLiteral("Westminster")
      << QStringLiteral("Weston")
      << QStringLiteral("Weymouth Town")
      << QStringLiteral("Wheaton")
      << QStringLiteral("Wheeling")
      << QStringLiteral("White Plains")
      << QStringLiteral("Whittier")
      << QStringLiteral("Wichita")
      << QStringLiteral("Wichita Falls")
      << QStringLiteral("Wilkes-Barre")
      << QStringLiteral("Wilmington")
      << QStringLiteral("Wilson")
      << QStringLiteral("Winston-Salem")
      << QStringLiteral("Winter Garden")
      << QStringLiteral("Woburn")
      << QStringLiteral("Woodbury")
      << QStringLiteral("Woodland")
      << QStringLiteral("Woonsocket")
      << QStringLiteral("Worcester")
      << QStringLiteral("Wylie")
      << QStringLiteral("Wyoming")
      << QStringLiteral("Yakima")
      << QStringLiteral("Yonkers")
      << QStringLiteral("Yorba Linda")
      << QStringLiteral("York")
      << QStringLiteral("Youngstown")
      << QStringLiteral("Yuba City")
      << QStringLiteral("Yucaipa")
      << QStringLiteral("Yuma")
    ;
}


void CRandomizer::buildCountryList() {
  _allCountries
    << QStringLiteral("China")
    << QStringLiteral("India")
    << QStringLiteral("USA")
    << QStringLiteral("Indonesia")
    << QStringLiteral("Brazil")
    << QStringLiteral("Pakistan")
    << QStringLiteral("Nigeria")
    << QStringLiteral("Bangladesh")
    << QStringLiteral("Russia")
    << QStringLiteral("Mexico")
    << QStringLiteral("Japan")
    << QStringLiteral("Ethiopia")
    << QStringLiteral("Philippines")
    << QStringLiteral("Egypt")
    << QStringLiteral("Vietnam")
    << QStringLiteral("Germany")
    << QStringLiteral("Congo")
    << QStringLiteral("Iran")
    << QStringLiteral("Turkey")
    << QStringLiteral("Thailand")
    << QStringLiteral("UK")
    << QStringLiteral("France")
    << QStringLiteral("Italy")
    << QStringLiteral("Tanzania")
    << QStringLiteral("South Africa")
    << QStringLiteral("Myanmar")
    << QStringLiteral("South Korea")
    << QStringLiteral("Colombia")
    << QStringLiteral("Kenya")
    << QStringLiteral("Spain")
    << QStringLiteral("Argentina")
    << QStringLiteral("Ukraine")
    << QStringLiteral("Uganda")
    << QStringLiteral("Algeria")
    << QStringLiteral("Sudan")
    << QStringLiteral("Iraq")
    << QStringLiteral("Poland")
    << QStringLiteral("Canada")
    << QStringLiteral("Morocco")
    << QStringLiteral("Afghanistan")
    << QStringLiteral("Saudi Arabia")
    << QStringLiteral("Peru")
    << QStringLiteral("Venezuela")
    << QStringLiteral("Uzbekistan")
    << QStringLiteral("Malaysia")
    << QStringLiteral("Angola")
    << QStringLiteral("Mozambique")
    << QStringLiteral("Nepal")
    << QStringLiteral("Ghana")
    << QStringLiteral("Yemen")
    << QStringLiteral("Madagascar")
    << QStringLiteral("North Korea")
    << QStringLiteral("Australia")
    << QStringLiteral("Ivory Coast")
    << QStringLiteral("Cameroon")
    << QStringLiteral("Taiwan")
    << QStringLiteral("Niger")
    << QStringLiteral("Sri Lanka")
    << QStringLiteral("Romania")
    << QStringLiteral("Burkina Faso")
    << QStringLiteral("Malawi")
    << QStringLiteral("Mali")
    << QStringLiteral("Syria")
    << QStringLiteral("Kazakhstan")
    << QStringLiteral("Chile")
    << QStringLiteral("Zambia")
    << QStringLiteral("Netherlands")
    << QStringLiteral("Guatemala")
    << QStringLiteral("Ecuador")
    << QStringLiteral("Zimbabwe")
    << QStringLiteral("Cambodia")
    << QStringLiteral("Senegal")
    << QStringLiteral("Chad")
    << QStringLiteral("Somalia")
    << QStringLiteral("Guinea")
    << QStringLiteral("South Sudan")
    << QStringLiteral("Rwanda")
    << QStringLiteral("Tunisia")
    << QStringLiteral("Cuba")
    << QStringLiteral("Belgium")
    << QStringLiteral("Benin")
    << QStringLiteral("Greece")
    << QStringLiteral("Bolivia")
    << QStringLiteral("Haiti")
    << QStringLiteral("Burundi")
    << QStringLiteral("Dominican Republic")
    << QStringLiteral("Czech Republic")
    << QStringLiteral("Portugal")
    << QStringLiteral("Sweden")
    << QStringLiteral("Azerbaijan")
    << QStringLiteral("Hungary")
    << QStringLiteral("Jordan")
    << QStringLiteral("Belarus")
    << QStringLiteral("UAE")
    << QStringLiteral("Honduras")
    << QStringLiteral("Tajikistan")
    << QStringLiteral("Serbia")
    << QStringLiteral("Austria")
    << QStringLiteral("Switzerland")
    << QStringLiteral("Israel")
    << QStringLiteral("Papua New Guinea")
    << QStringLiteral("Togo")
    << QStringLiteral("Sierra Leone")
    << QStringLiteral("Hong Kong")
    << QStringLiteral("Bulgaria")
    << QStringLiteral("Laos")
    << QStringLiteral("Paraguay")
    << QStringLiteral("El Salvador")
    << QStringLiteral("Libya")
    << QStringLiteral("Nicaragua")
    << QStringLiteral("Lebanon")
    << QStringLiteral("Kyrgyzstan")
    << QStringLiteral("Turkmenistan")
    << QStringLiteral("Denmark")
    << QStringLiteral("Singapore")
    << QStringLiteral("Finland")
    << QStringLiteral("Slovakia")
    << QStringLiteral("Norway")
    << QStringLiteral("Congo")
    << QStringLiteral("Eritrea")
    << QStringLiteral("Costa Rica")
    << QStringLiteral("Ireland")
    << QStringLiteral("Liberia")
    << QStringLiteral("New Zealand")
    << QStringLiteral("Oman")
    << QStringLiteral("Mauritania")
    << QStringLiteral("Croatia")
    << QStringLiteral("Kuwait")
    << QStringLiteral("Panama")
    << QStringLiteral("Moldova")
    << QStringLiteral("Georgia")
    << QStringLiteral("Puerto Rico")
    << QStringLiteral("Bosnia")
    << QStringLiteral("Herzegovina")
    << QStringLiteral("Uruguay")
    << QStringLiteral("Mongolia")
    << QStringLiteral("Armenia")
    << QStringLiteral("Albania")
    << QStringLiteral("Jamaica")
    << QStringLiteral("Lithuania")
    << QStringLiteral("Qatar")
    << QStringLiteral("Namibia")
    << QStringLiteral("Botswana")
    << QStringLiteral("Lesotho")
    << QStringLiteral("Gambia")
    << QStringLiteral("Macedonia")
    << QStringLiteral("Slovenia")
    << QStringLiteral("Gabon")
    << QStringLiteral("Latvia")
    << QStringLiteral("Guinea-Bissau")
    << QStringLiteral("Bahrain")
    << QStringLiteral("Trinidad")
    << QStringLiteral("Tobago")
    << QStringLiteral("Eswatini")
    << QStringLiteral("Estonia")
    << QStringLiteral("East Timor")
    << QStringLiteral("Equatorial ")
    << QStringLiteral("Mauritius")
    << QStringLiteral("Cyprus")
    << QStringLiteral("Djibouti")
    << QStringLiteral("Fiji")
    << QStringLiteral("Reunion")
    << QStringLiteral("Comoros")
    << QStringLiteral("Bhutan")
    << QStringLiteral("Guyana")
    << QStringLiteral("Montenegro")
    << QStringLiteral("Macau")
    << QStringLiteral("Solomon")
    << QStringLiteral("Luxembourg")
    << QStringLiteral("Suriname")
    << QStringLiteral("Sahara")
    << QStringLiteral("Cape Verde")
    << QStringLiteral("Guadeloupe")
    << QStringLiteral("Maldives")
    << QStringLiteral("Malta")
    << QStringLiteral("Brunei")
    << QStringLiteral("Bahamas")
    << QStringLiteral("Martinique")
    << QStringLiteral("Belize")
    << QStringLiteral("Iceland")
    << QStringLiteral("Barbados")
    << QStringLiteral("Polynesia")
    << QStringLiteral("Guiana")
    << QStringLiteral("Vanuatu")
    << QStringLiteral("Mayotte")
    << QStringLiteral("Samoa")
    << QStringLiteral("Saint Lucia")
    << QStringLiteral("Guernsey")
    << QStringLiteral("Jersey")
    << QStringLiteral("Guam")
    << QStringLiteral("Kiribati")
    << QStringLiteral("Saint Vincent")
    << QStringLiteral("Tonga")
    << QStringLiteral("Grenada")
    << QStringLiteral("Micronesia")
    << QStringLiteral("Aruba")
    << QStringLiteral("Antigua")
    << QStringLiteral("Barbuda")
    << QStringLiteral("Seychelles")
    << QStringLiteral("Man")
    << QStringLiteral("Andorra")
    << QStringLiteral("Dominica")
    << QStringLiteral("Bermuda")
    << QStringLiteral("Greenland")
    << QStringLiteral("Samoa")
    << QStringLiteral("Marshall")
    << QStringLiteral("Faroe")
    << QStringLiteral("Sint Maarten")
    << QStringLiteral("Monaco")
    << QStringLiteral("Liechtenstein")
    << QStringLiteral("Gibraltar")
    << QStringLiteral("San Marino")
    << QStringLiteral("Palau")
    << QStringLiteral("Cook")
    << QStringLiteral("Anguilla")
    << QStringLiteral("Wallis")
    << QStringLiteral("Futuna")
    << QStringLiteral("Nauru")
    << QStringLiteral("Tuvalu")
    << QStringLiteral("Montserrat")
    << QStringLiteral("Falkland")
    << QStringLiteral("Niue")
    << QStringLiteral("Tokelau")
    << QStringLiteral("Vatican")
  ;
}

void CRandomizer::buildFoodList() {
  _allFoods
    << QStringLiteral("Acai berry")
    << QStringLiteral("Adzuki bean")
    << QStringLiteral("Almonds")
    << QStringLiteral("Amaranth")
    << QStringLiteral("Anchovy")
    << QStringLiteral("Apple")
    << QStringLiteral("Apricot")
    << QStringLiteral("Artichoke")
    << QStringLiteral("Arugula")
    << QStringLiteral("Asian pear")
    << QStringLiteral("Asparagus")
    << QStringLiteral("Autumn olive")
    << QStringLiteral("Avocado")
    << QStringLiteral("Bachelors buttons")
    << QStringLiteral("Bacon")
    << QStringLiteral("Banana")
    << QStringLiteral("Barley")
    << QStringLiteral("Basil")
    << QStringLiteral("Basswood")
    << QStringLiteral("Bean")
    << QStringLiteral("Bee balm")
    << QStringLiteral("Beef")
    << QStringLiteral("Beets")
    << QStringLiteral("Bilberry")
    << QStringLiteral("Bitter melon")
    << QStringLiteral("Black walnut")
    << QStringLiteral("Blackberry")
    << QStringLiteral("Blackeyed peas")
    << QStringLiteral("Blueberry")
    << QStringLiteral("Bok choy")
    << QStringLiteral("Bonefish")
    << QStringLiteral("Boniato")
    << QStringLiteral("Brazil nut")
    << QStringLiteral("Broccoli")
    << QStringLiteral("Brussels sprouts")
    << QStringLiteral("Buckwheat")
    << QStringLiteral("Burdock")
    << QStringLiteral("Burger")
    << QStringLiteral("Butternut")
    << QStringLiteral("Butternut squash")
    << QStringLiteral("Cabbage")
    << QStringLiteral("Calabash gourd")
    << QStringLiteral("Canola")
    << QStringLiteral("Cantaloupe")
    << QStringLiteral("Cardamom")
    << QStringLiteral("Carob")
    << QStringLiteral("Carrots")
    << QStringLiteral("Cashew")
    << QStringLiteral("Cassava")
    << QStringLiteral("Cattail roots and shoots")
    << QStringLiteral("Cauliflower")
    << QStringLiteral("Cayenne pepper")
    << QStringLiteral("Celeriac")
    << QStringLiteral("Celery")
    << QStringLiteral("Chamomile")
    << QStringLiteral("Chard")
    << QStringLiteral("Cheese")
    << QStringLiteral("Cherimoya")
    << QStringLiteral("Cherry")
    << QStringLiteral("Chia")
    << QStringLiteral("Chicken")
    << QStringLiteral("Chickweed")
    << QStringLiteral("Chicory")
    << QStringLiteral("Chili pepper")
    << QStringLiteral("Chinese cabbage")
    << QStringLiteral("Chinese long bean")
    << QStringLiteral("Chives")
    << QStringLiteral("Chocolate")
    << QStringLiteral("Choke cherry")
    << QStringLiteral("Choy sum")
    << QStringLiteral("Chrysanthemum")
    << QStringLiteral("Cilantro")
    << QStringLiteral("Cinnamon")
    << QStringLiteral("Cloudberry")
    << QStringLiteral("Clove")
    << QStringLiteral("Coco malanga")
    << QStringLiteral("Coconut")
    << QStringLiteral("Codfish")
    << QStringLiteral("Collards")
    << QStringLiteral("Comfrey")
    << QStringLiteral("Corn")
    << QStringLiteral("Cranberry")
    << QStringLiteral("Cucumber")
    << QStringLiteral("Culantro")
    << QStringLiteral("Cumin")
    << QStringLiteral("Currant")
    << QStringLiteral("Dandelion")
    << QStringLiteral("Dates")
    << QStringLiteral("Day lily")
    << QStringLiteral("Dill")
    << QStringLiteral("Dragon fruit")
    << QStringLiteral("Dulse")
    << QStringLiteral("Eddoe")
    << QStringLiteral("Eggplant")
    << QStringLiteral("Eggs")
    << QStringLiteral("Elder")
    << QStringLiteral("Eleuthero")
    << QStringLiteral("Enoki mushrooms")
    << QStringLiteral("Evening primrose")
    << QStringLiteral("Fennel")
    << QStringLiteral("Fenugreek")
    << QStringLiteral("Field sorrel")
    << QStringLiteral("Fig")
    << QStringLiteral("Flax")
    << QStringLiteral("Gai choy")
    << QStringLiteral("Gai laan")
    << QStringLiteral("Garbanzo beans")
    << QStringLiteral("Garlic")
    << QStringLiteral("Garlic mustard")
    << QStringLiteral("Ginger")
    << QStringLiteral("Gingko")
    << QStringLiteral("Goji berry")
    << QStringLiteral("Gooseberry")
    << QStringLiteral("Grapefruit")
    << QStringLiteral("Grapes")
    << QStringLiteral("Ground mallow")
    << QStringLiteral("Haggis")
    << QStringLiteral("Ham")
    << QStringLiteral("Hazelnut")
    << QStringLiteral("Hibiscus")
    << QStringLiteral("Hickory nut")
    << QStringLiteral("Highbush cranberry")
    << QStringLiteral("Honey")
    << QStringLiteral("Honeybush")
    << QStringLiteral("Honeydew melon")
    << QStringLiteral("Horsemint")
    << QStringLiteral("Horseradish")
    << QStringLiteral("Hot dog")
    << QStringLiteral("Hyssop")
    << QStringLiteral("Jack fruit")
    << QStringLiteral("Jerusalem artichoke")
    << QStringLiteral("Jicama")
    << QStringLiteral("Kale")
    << QStringLiteral("Kelp")
    << QStringLiteral("Kiwano melon")
    << QStringLiteral("Kiwi")
    << QStringLiteral("Kohlrabi")
    << QStringLiteral("Kombucha")
    << QStringLiteral("Lambsquarters")
    << QStringLiteral("Lavender")
    << QStringLiteral("Leeks")
    << QStringLiteral("Lemon")
    << QStringLiteral("Lemon balm")
    << QStringLiteral("Lemon grass")
    << QStringLiteral("Lemon verbena")
    << QStringLiteral("Lentils")
    << QStringLiteral("Lettuce")
    << QStringLiteral("Licorice root")
    << QStringLiteral("Lilac")
    << QStringLiteral("Lime")
    << QStringLiteral("Lions mane mushrooms")
    << QStringLiteral("Longan berries")
    << QStringLiteral("Lotus")
    << QStringLiteral("Lychee")
    << QStringLiteral("Mache")
    << QStringLiteral("Maitake mushrooms")
    << QStringLiteral("Maize")
    << QStringLiteral("Malabar spinach")
    << QStringLiteral("Malanga")
    << QStringLiteral("Mandarin")
    << QStringLiteral("Mango")
    << QStringLiteral("Mangosteen")
    << QStringLiteral("Maple")
    << QStringLiteral("Millet")
    << QStringLiteral("Mint")
    << QStringLiteral("Mizuna")
    << QStringLiteral("Mo qua")
    << QStringLiteral("Monarda")
    << QStringLiteral("Morel mushroom")
    << QStringLiteral("Mustard")
    << QStringLiteral("Name yam")
    << QStringLiteral("Nectarine")
    << QStringLiteral("Nettle")
    << QStringLiteral("Nira")
    << QStringLiteral("Noni")
    << QStringLiteral("Nori seaweed")
    << QStringLiteral("Nutmeg")
    << QStringLiteral("Nutritional yeast")
    << QStringLiteral("Oats")
    << QStringLiteral("Octopus")
    << QStringLiteral("Okra")
    << QStringLiteral("Olive")
    << QStringLiteral("Onion")
    << QStringLiteral("Orange")
    << QStringLiteral("Oregano")
    << QStringLiteral("Oyster mushroom")
    << QStringLiteral("Pak choy")
    << QStringLiteral("Panax ginseng")
    << QStringLiteral("Papaya")
    << QStringLiteral("Parsley")
    << QStringLiteral("Parsnips")
    << QStringLiteral("Peaches")
    << QStringLiteral("Peanuts")
    << QStringLiteral("Pear")
    << QStringLiteral("Peas")
    << QStringLiteral("Pecan")
    << QStringLiteral("Pepino melon")
    << QStringLiteral("Pepper")
    << QStringLiteral("Peppermint")
    << QStringLiteral("Persimmon")
    << QStringLiteral("Pine nuts")
    << QStringLiteral("Pineapple")
    << QStringLiteral("Pistachio")
    << QStringLiteral("Plantain")
    << QStringLiteral("Plum")
    << QStringLiteral("Pomegranate")
    << QStringLiteral("Pomelo")
    << QStringLiteral("Porcini mushrooms")
    << QStringLiteral("Pork")
    << QStringLiteral("Porkchop")
    << QStringLiteral("Portobella mushroom")
    << QStringLiteral("Potatoes")
    << QStringLiteral("Pumpkin")
    << QStringLiteral("Purslane")
    << QStringLiteral("Quinoa")
    << QStringLiteral("Radicchio")
    << QStringLiteral("Radish")
    << QStringLiteral("Rambutan")
    << QStringLiteral("Raspberry")
    << QStringLiteral("Rhubarb")
    << QStringLiteral("Rice")
    << QStringLiteral("Roast")
    << QStringLiteral("Rose")
    << QStringLiteral("Rutabaga")
    << QStringLiteral("Rye")
    << QStringLiteral("Safflower")
    << QStringLiteral("Sage")
    << QStringLiteral("Salmon")
    << QStringLiteral("Salsify")
    << QStringLiteral("Sapote")
    << QStringLiteral("Sarsaparilla")
    << QStringLiteral("Sausage")
    << QStringLiteral("Sclopit")
    << QStringLiteral("Seabuckthorn")
    << QStringLiteral("Senposai greens")
    << QStringLiteral("Serrano pepper")
    << QStringLiteral("Serviceberry")
    << QStringLiteral("Sesame")
    << QStringLiteral("Shallots")
    << QStringLiteral("Shiitake mushroom")
    << QStringLiteral("Sorghum")
    << QStringLiteral("Soy")
    << QStringLiteral("Spaghetti squash")
    << QStringLiteral("Spearamint")
    << QStringLiteral("Spinach")
    << QStringLiteral("Spirulina")
    << QStringLiteral("Star anise")
    << QStringLiteral("Stevia")
    << QStringLiteral("Strawberry")
    << QStringLiteral("Sugar cane")
    << QStringLiteral("Sumac")
    << QStringLiteral("Summer squash")
    << QStringLiteral("Sunflower")
    << QStringLiteral("Sweet peppers")
    << QStringLiteral("Sweet potato")
    << QStringLiteral("Tamarillo")
    << QStringLiteral("Tamarind")
    << QStringLiteral("Tapioca")
    << QStringLiteral("Taro")
    << QStringLiteral("Tatsoi")
    << QStringLiteral("Tea")
    << QStringLiteral("Thistle")
    << QStringLiteral("Thyme")
    << QStringLiteral("Tomatillo")
    << QStringLiteral("Tomato")
    << QStringLiteral("Trout lily")
    << QStringLiteral("Tuna")
    << QStringLiteral("Turkey")
    << QStringLiteral("Turmeric")
    << QStringLiteral("Turnip")
    << QStringLiteral("Unagi eel")
    << QStringLiteral("Vanilla")
    << QStringLiteral("Venison")
    << QStringLiteral("Violets")
    << QStringLiteral("Wakame")
    << QStringLiteral("Walnut")
    << QStringLiteral("Water chestnuts")
    << QStringLiteral("Watercress")
    << QStringLiteral("Watermelon")
    << QStringLiteral("Watermint")
    << QStringLiteral("Wheat")
    << QStringLiteral("Winter squash")
    << QStringLiteral("Woodland sorrel")
    << QStringLiteral("Yam")
    << QStringLiteral("Yarrow")
    << QStringLiteral("Yellow squash")
    << QStringLiteral("Yerba mate")
    << QStringLiteral("Yo choy sum")
    << QStringLiteral("Yumberry")
    << QStringLiteral("Zucchini")
  ;
}
